import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'te';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.listService': 'List your Service',
    'nav.loginRegister': 'Login/Register',
    'nav.logout': 'Logout',
    'nav.meelova': 'Meelova',
    
    // Locations
    'location.gachibowli': 'Gachibowli',
    'location.hiTechCity': 'Hi-Tech City',
    'location.jubileeHills': 'Jubilee Hills',
    'location.banjaraHills': 'Banjara Hills',
    
    // Hero
    'hero.title': 'Your Event, Perfected',
    'hero.subtitle': 'Find the perfect venue and services for your special day',
    'hero.getStarted': 'Get Started',
    
    // Search
    'search.location': 'Location',
    'search.dateTime': 'Date&Time',
    'search.topCategories': 'Top Categories',
    'search.button': 'Search',
    
    // Why Meelova Section
    'whyMeelova.title': 'Why Meelova?',
    'whyMeelova.description': 'Meelova bridges the gap between your dream events and trusted service providers. From weddings to corporate gatherings, we connect you with verified vendors who bring your vision to life.',
    'whyMeelova.easyDiscovery': 'Easy Discovery',
    'whyMeelova.easyDiscoveryDesc': 'Browse through hundreds of verified vendors across multiple categories to find the perfect match for your event.',
    'whyMeelova.trustedPartners': 'Trusted Partners',
    'whyMeelova.trustedPartnersDesc': 'All vendors are verified with genuine ratings and reviews from real customers to ensure quality service.',
    'whyMeelova.seamlessBooking': 'Seamless Booking',
    'whyMeelova.seamlessBookingDesc': 'Request services, confirm bookings, and manage everything in one place. Your perfect event is just clicks away.',
    
    // Steps of Process
    'steps.title': 'STEPS OF PROCESS',
    'steps.signUp': 'Sign Up or Log In',
    'steps.signUpDesc': 'to Get Started',
    'steps.discover': 'Discover services',
    'steps.discoverDesc': 'for your event',
    'steps.findService': 'Find the Right Service',
    'steps.findServiceDesc': 'Provider and Send a Request',
    'steps.confirm': 'Confirm with provider,',
    'steps.confirmDesc': 'pay advance',
    'steps.enjoy': 'Finally, enjoy your',
    'steps.enjoyDesc': 'perfect event',
    
    // Vendor Statistics
    'vendorStats.title': 'NO. OF VENDORS PER CATEGORY',
    'vendorStats.venue': 'Venue',
    'vendorStats.decorator': 'Decorator',
    'vendorStats.photography': 'Photography',
    'vendorStats.djMusic': 'DJ & Music',
    'vendorStats.makeup': 'Makeup',
    'vendorStats.catering': 'Catering',
    
    // Event Types
    'events.title': 'Plan by Event',
    'events.wedding': 'Wedding',
    'events.birthday': 'Birthday Party',
    'events.reception': 'Reception',
    'events.houseWarming': 'House Warming',
    'events.engagement': 'Engagement',
    'events.corporate': 'Corporate Event',
    'events.viewDetails': 'View Details',
    'events.allEventTypes': 'All Event Types',
    'events.browseVendors': 'Browse trusted vendors for your {event} and make your event memorable.',
    'events.readyToBook': 'Ready to Book Your Event?',
    'events.loginToAccess': 'Login to access our complete vendor list and book your perfect event services',
    'events.loginToBookServices': 'Login to Book Services',
    
    // Featured Vendors
    'vendors.title': 'Featured Vendors',
    'vendors.viewAll': 'View All',
    'vendors.viewDetails': 'View Details',
    'vendors.loginToBook': 'Login to Book Service',
    'vendors.close': 'Close',
    'vendors.about': 'About',
    'vendors.servicesOffered': 'Services Offered',
    'vendors.capacity': 'Capacity',
    'vendors.priceRange': 'Price Range',
    'vendors.amenities': 'Amenities',
    'vendors.loginPrompt': 'To book this service, please login to your account',
    
    // Footer
    'footer.tagline': 'Your Event, Perfected',
    'footer.quickLinks': 'Quick Links',
    'footer.aboutUs': 'About Us',
    'footer.listServices': 'List Your Services',
    'footer.faqs': 'FAQs',
    'footer.contactUs': 'Contact Us',
    'footer.getInTouch': 'Get In Touch',
    'footer.findService': 'FIND YOUR SERVICE',
    'footer.allRightsReserved': 'All rights reserved.',
    
    // Search Results
    'search.results': 'Search Results',
    'search.filters': 'Filters',
    'search.found': 'Found',
    'search.vendors': 'vendors',
    'search.noResults': 'No vendors found matching your criteria',
    'search.backToHome': 'Back to Home',
    'search.category': 'Category',
    
    // Event Details
    'eventDetails.whatWeOffer': 'What We Offer',
    'eventDetails.relatedVendors': 'Related Vendors',
    
    // Help Center
    'helpCenter.title': 'Help Center',
    'helpCenter.placeholder': 'Type your question...',
    
    // Search Date/Time
    'search.selectDate': 'Select Date',
    'search.selectTime': 'Select Time',
    
    // Vendor Landing
    'vendor.listYour': 'List your',
    'vendor.onMeelova': 'On Meelova.in',
    'vendor.tagline': 'Meelova is India\'s premier event booking platform that connects clients for every occasion.',
    'vendor.registerFree': 'Register for free',
    'vendor.genuineLeads': 'Genuine leads and booking',
    'vendor.securePayments': 'Secure and fast payments',
    'vendor.customerService': '24/7 Customer service',
    'vendor.registerNow': 'Register now',
    'vendor.whyPartner': 'Why partner with Meelova',
    'vendor.faqs': 'Frequently Asked Questions',
    'vendor.faq1': 'What are the commission rates?',
    'vendor.faq1Answer': 'We charge a competitive 10-15% commission on confirmed bookings. There are no hidden fees or upfront costs.',
    'vendor.faq2': 'How do I get started as a vendor?',
    'vendor.faq2Answer': 'Simply click \'Register Now\', fill in your business details, upload service photos, and start receiving booking requests within 24 hours of approval.',
    'vendor.faq3': 'Can I cancel bookings if needed?',
    'vendor.faq3Answer': 'Yes, you can cancel bookings through your dashboard. However, repeated cancellations may affect your ratings and visibility on the platform.',
    'vendor.faq4': 'How quickly do I receive payments?',
    'vendor.faq4Answer': 'Payments are transferred within 24-48 hours after successful event completion. You can track all payments in your wallet dashboard.',
    'vendor.faq5': 'What kind of support do you provide?',
    'vendor.faq5Answer': 'We offer 24/7 customer support via phone, email, and in-app chat. Our dedicated vendor success team helps with onboarding, optimization, and resolving any issues.',
    'vendor.faq6': 'Can I add multiple services under one account?',
    'vendor.faq6Answer': 'Absolutely! You can list unlimited services under one vendor account, from catering to photography to decoration services.',
    
    // Vendor Landing Page Additional
    'vendor.verifiedLeads': 'Verified leads',
    'vendor.verifiedLeadsDesc': 'Get access to genuine, instant verified leads from real clients ready to book.',
    'vendor.instantPayments': 'Instant payments',
    'vendor.instantPaymentsDesc': 'Instant payment transfers—no delays, no waiting.',
    'vendor.smartDashboard': 'Smart Dashboard',
    'vendor.smartDashboardDesc': 'All your leads, bookings, and payments in one smart dashboard.',
    'vendor.growBusiness': 'Grow your Business',
    'vendor.growBusinessDesc': 'Grow your business and reach more clients with Meelova.',
    'vendor.clientChat': 'Client chat',
    'vendor.clientChatDesc': 'Direct communication with clients.',
    'vendor.howToEnroll': 'How to Enroll Your Service',
    'vendor.getStartedSteps': 'Get started in just 5 simple steps',
    'vendor.createAccount': 'Create Account',
    'vendor.createAccountDesc': 'Sign up with your business details and get verified quickly',
    'vendor.addServiceDetails': 'Add Service Details',
    'vendor.addServiceDetailsDesc': 'Upload high-quality photos and describe your services',
    'vendor.setPricing': 'Set Pricing',
    'vendor.setPricingDesc': 'Define your competitive rates and availability calendar',
    'vendor.getVerified': 'Get Verified',
    'vendor.getVerifiedDesc': 'Complete our quick verification process for trust',
    'vendor.startReceiving': 'Start Receiving',
    'vendor.startReceivingDesc': 'Get bookings from verified clients immediately',
    'vendor.securePaymentsTitle': 'Secure & Transparent Payments',
    'vendor.securePaymentsSubtitle': 'Experience hassle-free payments with industry-leading security and transparency',
    'vendor.instantPayouts': 'Instant payouts',
    'vendor.instantPayoutsDesc': 'Get paid immediately after service completion with our automated payment system.',
    'vendor.earningDashboard': 'Earning dashboard',
    'vendor.earningDashboardDesc': 'Track your income, performance metrics, and growth analytics in real-time.',
    'vendor.paymentsMadeEasy': 'Payments made easy',
    'vendor.paymentsMadeEasyDesc': 'Smooth, fast and easy payments for all your services.',
    'vendor.automatedInvoicing': 'Automated Invoicing',
    'vendor.automatedInvoicingDesc': 'Professional invoices generated automatically with tax compliance.',
    'vendor.supportedPayments': 'Supported Payment Methods',
    'vendor.whatVendorsSay': 'What Our Vendors Say',
    'vendor.testimonial1': 'Joining this platform transformed my catering business. The streamlined booking process and client management tools have made it easier to connect with clients, leading to an increase in bookings. Highly recommended!',
    'vendor.testimonial1Name': 'Emily Johnson',
    'vendor.testimonial1Role': 'Owner of Gourmet Delights Catering',
    'vendor.testimonial2': 'As a photographer, I struggled to find clients. This platform not only connected me with event planners but also provided valuable insights into my bookings. The support team is phenomenal!',
    'vendor.testimonial2Name': 'Michael Chen',
    'vendor.testimonial2Role': 'Freelance Photographer',
    'vendor.testimonial3': 'I\'ve been able to showcase my decoration services to a wider audience. The user-friendly interface and responsive customer service have made all the difference in my business growth.',
    'vendor.testimonial3Name': 'Sofia Patel',
    'vendor.testimonial3Role': 'Event Decorator',
    'vendor.trustedPartners': 'Trusted Partners with Meelova',
    'vendor.faqTitle': 'Frequently Asked Questions',
    'vendor.faqSubtitle': 'Everything you need to know about getting started',
    'vendor.marketSize': 'Market size',
    'vendor.marketValue': 'Indian market value',
    'vendor.eventsPerDay': 'Events happening per day in India',
    'vendor.projected': 'Projected (2025–2028)',
    'vendor.footerTagline': 'India\'s largest event and entertainment management platform connecting vendors with clients. Build your business with verified leads and secure payments.',
    'vendor.contactUs': 'Contact us',
    'vendor.copyright': '© 2025 Meelova. All rights reserved.',
    'vendor.venue': 'Venue',
    'vendor.djSound': 'DJ Sound',
    'vendor.cateringService': 'Catering',
    'vendor.photography': 'Photography',
    'vendor.decorationService': 'Decoration',
    'vendor.musicBand': 'Music Band',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.bookings': 'Bookings',
    'dashboard.myServices': 'My Services',
    'dashboard.addService': 'Add New Service',
    'dashboard.wallet': 'Wallet',
    'dashboard.messages': 'Messages',
    'dashboard.settings': 'Settings',
    'dashboard.eAlbum': 'E-Album',
    
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Login to your Meelova account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.button': 'Login',
    'login.noAccount': "Don't have an account?",
    'login.signupLink': 'Sign up',
    
    // Signup
    'signup.title': 'Create Account',
    'signup.subtitle': 'Join Meelova today',
    'signup.name': 'Full Name',
    'signup.email': 'Email',
    'signup.password': 'Password',
    'signup.button': 'Sign Up',
    'signup.hasAccount': 'Already have an account?',
    'signup.loginLink': 'Login',
    
    // Vendor Registration
    'vendorReg.title': 'Vendor Registration',
    'vendorReg.profile': 'Profile',
    'vendorReg.documents': 'Documents',
    'vendorReg.portfolio': 'Portfolio',
    'vendorReg.pricing': 'Pricing',
    'vendorReg.step': 'Step',
    'vendorReg.businessName': 'Business Name',
    'vendorReg.ownerName': 'Owner Name',
    'vendorReg.phone': 'Phone Number',
    'vendorReg.category': 'Service Category',
    'vendorReg.address': 'Business Address',
    'vendorReg.description': 'Business Description',
    'vendorReg.previous': 'Previous',
    'vendorReg.next': 'Next',
    'vendorReg.goToDashboard': 'Go to Dashboard',
    'vendorReg.panCard': 'PAN Card',
    'vendorReg.aadhaarCard': 'Aadhaar Card',
    'vendorReg.gstCertificate': 'GST Certificate (if applicable)',
    'vendorReg.businessLicense': 'Business License/Registration',
    'vendorReg.bankProof': 'Bank Account Proof',
    'vendorReg.workImages': 'Work Showcase Images',
    'vendorReg.certificates': 'Certificates & Awards',
    'vendorReg.workHistory': 'Work History',
    'vendorReg.socialMedia': 'Social Media Links',
    'vendorReg.serviceName': 'Service Name',
    'vendorReg.basePrice': 'Base Price (₹)',
    'vendorReg.capacity': 'Capacity',
    'vendorReg.pricingDescription': 'Pricing Description',
    'vendorReg.advancePayment': 'Advance Payment Required (%)',
    'vendorReg.cancellationPolicy': 'Cancellation Policy',
    'vendorReg.availability': 'Availability',
    'vendorReg.uploadPan': 'Upload clear copy of PAN card',
    'vendorReg.uploadAadhaar': 'Upload front and back of Aadhaar',
    'vendorReg.uploadGst': 'Upload GST registration certificate',
    'vendorReg.uploadBusinessDoc': 'Any business registration document',
    'vendorReg.uploadBankProof': 'Cancelled cheque or bank statement',
    'vendorReg.uploadWorkImages': 'Upload at least 5 high-quality images of your work (max 20 images)',
    'vendorReg.uploadCertificates': 'Any awards, certificates, or achievements',
    'vendorReg.workHistoryPlaceholder': 'Describe your experience, notable events, clients...',
    'vendorReg.instagramPlaceholder': 'Instagram profile URL',
    'vendorReg.facebookPlaceholder': 'Facebook page URL',
    'vendorReg.websitePlaceholder': 'Website URL (if any)',
    'vendorReg.serviceNamePlaceholder': 'e.g., Basic Package, Premium Package',
    'vendorReg.basePricePlaceholder': '50000',
    'vendorReg.capacityPlaceholder': '200 persons',
    'vendorReg.pricingDescPlaceholder': 'What\'s included at this price? Any extra charges?',
    'vendorReg.advancePaymentPlaceholder': '30',
    'vendorReg.advancePaymentHelper': 'Percentage of advance payment required for booking',
    'vendorReg.cancellationPlaceholder': 'Describe your cancellation and refund policy',
    'vendorReg.availabilityPlaceholder': 'Your working days, hours, blackout dates...',
    'vendorReg.registrationComplete': 'Registration Complete!',
    'vendorReg.registrationSuccess': 'Your vendor account has been created successfully.',
    
    // Vendor Dashboard
    'vendorDash.title': 'Vendor Dashboard',
    'vendorDash.dashboard': 'Dashboard',
    'vendorDash.bookings': 'Bookings',
    'vendorDash.services': 'My Services',
    'vendorDash.addService': 'Add New Service',
    'vendorDash.wallet': 'Wallet',
    'vendorDash.messages': 'Messages',
    'vendorDash.settings': 'Settings',
    'vendorDash.profile': 'Profile',
    'vendorDash.logout': 'Logout',
    'vendorDash.totalEarnings': 'Total Earnings',
    'vendorDash.activeBookings': 'Active Bookings',
    'vendorDash.totalClients': 'Total Clients',
    'vendorDash.pendingRequests': 'Pending Requests',
    'vendorDash.fromLastMonth': '+20% from last month',
    'vendorDash.fromLastWeek': '+3 from last week',
    'vendorDash.newThisMonth': '+8 new this month',
    'vendorDash.respondQuickly': 'Respond quickly',
    'vendorDash.earningsOverview': 'Earnings Overview',
    'vendorDash.earningsOverviewDesc': 'Your monthly earnings for the last 6 months',
    'vendorDash.quickActions': 'Quick Actions',
    'vendorDash.addNewService': 'Add New Service',
    'vendorDash.viewBookings': 'View Bookings',
    'vendorDash.checkMessages': 'Check Messages',
    'vendorDash.myBookings': 'My Bookings',
    'vendorDash.myBookingsDesc': 'Manage your upcoming and past bookings',
    'vendorDash.weddingReception': 'Wedding Reception',
    'vendorDash.bookingDate': 'Date: 25th Dec 2025 | Client: John Doe',
    'vendorDash.viewDetailsBtn': 'View Details',
    'vendorDash.myServicesTitle': 'My Services',
    'vendorDash.myServicesDesc': 'Services you\'ve listed on the platform',
    'vendorDash.status': 'Status',
    'vendorDash.active': 'Active',
    'vendorDash.edit': 'Edit',
    'vendorDash.view': 'View',
    'vendorDash.addServiceTitle': 'Add New Service',
    'vendorDash.addServiceDesc': 'List a new service on the platform',
    'vendorDash.serviceName': 'Service Name',
    'vendorDash.serviceNamePlaceholder': 'e.g., Wedding Photography',
    'vendorDash.serviceDescription': 'Description',
    'vendorDash.serviceDescPlaceholder': 'Describe your service...',
    'vendorDash.price': 'Price (₹)',
    'vendorDash.serviceImages': 'Service Images',
    'vendorDash.clickToUpload': 'Click to upload images',
    'vendorDash.uploadLimit': 'PNG, JPG up to 10MB',
    'vendorDash.addServiceBtn': 'Add Service',
    'vendorDash.walletTitle': 'Wallet',
    'vendorDash.walletDesc': 'Manage your earnings and payments',
    'vendorDash.availableBalance': 'Available Balance',
    'vendorDash.withdrawFunds': 'Withdraw Funds',
    'vendorDash.recentTransactions': 'Recent Transactions',
    'vendorDash.paymentReceived': 'Payment Received',
    'vendorDash.messagesTitle': 'Messages',
    'vendorDash.messagesDesc': 'Chat with your clients',
    'vendorDash.client': 'Client',
    'vendorDash.lastMessagePreview': 'Last message preview...',
    'vendorDash.hoursAgo': '2h ago',
    'vendorDash.profileSettings': 'Profile Settings',
    'vendorDash.businessName': 'Business Name',
    'vendorDash.businessNamePlaceholder': 'Your Business Name',
    'vendorDash.email': 'Email',
    'vendorDash.emailPlaceholder': 'your@email.com',
    'vendorDash.phone': 'Phone',
    'vendorDash.phonePlaceholder': '+91 9876543210',
    'vendorDash.updateProfile': 'Update Profile',
    'vendorDash.language': 'Language',
    'vendorDash.selectLanguage': 'Select language',
    'vendorDash.notifications': 'Notifications',
    'vendorDash.emailNotifications': 'Email Notifications',
    'vendorDash.smsNotifications': 'SMS Notifications',
    'vendorDash.bookingAlerts': 'Booking Alerts',
    'vendorDash.weddingPhotography': 'Wedding Photography',
    'vendorDash.birthdayDecoration': 'Birthday Decoration',
    'vendorDash.corporateEventCatering': 'Corporate Event Catering',
    
    // Customer Dashboard
    'customerDash.filterBy': 'FILTER BY',
    'customerDash.eventType': 'Event Type',
    'customerDash.wedding': 'Wedding',
    'customerDash.reception': 'Reception',
    'customerDash.birthdayParty': 'Birthday Party',
    'customerDash.ceremonies': 'Ceremonies',
    'customerDash.anniversaries': 'Anniversaries',
    'customerDash.privateParties': 'Private Parties',
    'customerDash.priceRange': 'PRICE RANGE',
    'customerDash.dateTime': 'Date & Time',
    'customerDash.amenitiesFeatures': 'Amenities & Features',
    'customerDash.discoverVenue': 'Discover your perfect venue',
    'customerDash.viewDetails': 'View Details',
    'customerDash.requestService': 'Request Service',
    'customerDash.logout': 'Logout',
    'customerDash.perfectFor': 'Perfect for small parties',
    'customerDash.ac': 'Air Conditioning',
    'customerDash.parking': 'Parking',
    'customerDash.catering': 'Catering',
    'customerDash.wifi': 'WiFi',
    'customerDash.sound': 'Sound System',
    'customerDash.decoration': 'Decoration',
    'customerDash.close': 'Close',
    'customerDash.about': 'About',
    'customerDash.servicesOffered': 'Services Offered',
    'customerDash.capacity': 'Capacity',
    'customerDash.priceRangeLabel': 'Price Range',
    'customerDash.amenities': 'Amenities',
    'customerDash.bookNow': 'Book Now',
    'customerDash.guests': 'guests',
    'customerDash.meelova': 'Meelova',
    'customerDash.meelovaHi': 'मीलोवा',
    'customerDash.meelovaTe': 'మీలోవా',
    'customerDash.confirmBooking': 'Confirm Booking',
    'customerDash.requestSent': 'Your request has been sent!',
    'customerDash.waitForStatus': 'Please wait for the vendor to confirm your booking. You will receive a notification once the status is updated.',
    'customerDash.okGotIt': 'OK, Got it',
    'customerDash.cancel': 'Cancel',
    'customerDash.lights': 'Lights',
    'customerDash.stage': 'Stage Setup',
    'customerDash.floralDecor': 'Floral Decor',
    'customerDash.videoScreen': 'Video Screen',
    
    // Vendor data translations
    'vendor.royalPalace': 'Royal Palace Banquet Hall',
    'vendor.royalPalaceDesc': 'Exceptional service for your special moments',
    'vendor.royalPalaceFull': 'Royal Palace Banquet Hall is a premium venue offering world-class facilities for weddings, receptions, and corporate events. With a capacity of 500+ guests, elegant decor, and modern amenities including central AC, LED lighting, and professional sound systems.',
    'vendor.grandHeritage': 'Grand Heritage Wedding Venue',
    'vendor.grandHeritageDesc': 'Exceptional service for your special moments',
    'vendor.grandHeritageFull': 'Grand Heritage brings traditional elegance with modern amenities. Perfect for intimate weddings and grand receptions. Our experienced team ensures every detail is perfect for your special day.',
    'vendor.premiumGarden': 'Premium Garden Events',
    'vendor.premiumGardenDesc': 'Exceptional service for your special moments',
    'vendor.premiumGardenFull': 'Premium Garden Events specializes in outdoor celebrations with beautifully landscaped gardens. Ideal for day weddings, birthday parties, and themed events with natural ambiance.',
    'vendor.weddingVenue': 'Wedding Venue',
    'vendor.receptionHall': 'Reception Hall',
    'vendor.corporateEvents': 'Corporate Events',
    'vendor.weddingService': 'Wedding',
    'vendor.engagementService': 'Engagement',
    'vendor.receptionService': 'Reception',
    'vendor.outdoorEvents': 'Outdoor Events',
    'vendor.gardenWeddings': 'Garden Weddings',
    'vendor.birthdayParties': 'Birthday Parties',
    'vendor.centralAc': 'Central AC',
    'vendor.ledLighting': 'LED Lighting',
    'vendor.soundSystem': 'Sound System',
    'vendor.parkingAvailable': 'Parking',
    'vendor.cateringAvailable': 'Catering Available',
    'vendor.gardenArea': 'Garden Area',
    'vendor.decorativeLighting': 'Decorative Lighting',
    'vendor.inHouseCatering': 'In-house Catering',
    'vendor.valetParking': 'Valet Parking',
    'vendor.bridalRoom': 'Bridal Room',
    'vendor.landscapedGarden': 'Landscaped Garden',
    'vendor.outdoorLighting': 'Outdoor Lighting',
    'vendor.gazebo': 'Gazebo',
    'vendor.amplePar': 'Ample Parking',
    'vendor.flexibleCatering': 'Flexible Catering',
    'vendor.cashfree': 'Cashfree',
    'vendor.upi': 'UPI',
    'vendor.cards': 'Cards',
    
    // Vendor Dashboard History & Calendar
    'vendorDash.history': 'History',
    'vendorDash.historyDesc': 'View your past bookings and transactions',
    'vendorDash.calendar': 'Calendar',
    'vendorDash.calendarDesc': 'View your scheduled events',
    'vendorDash.cashOnSpot': 'Cash on Spot',
    'vendorDash.currentTransactions': 'Current Transactions',
    'vendorDash.noEventsToday': 'No events scheduled for this date',
    'vendorDash.completed': 'Completed',
    'vendorDash.pending': 'Pending',
    'vendorDash.serviceUpdated': 'Service updated successfully',
    'vendorDash.serviceDeleted': 'Service deleted successfully',
    'vendorDash.confirmDelete': 'Are you sure you want to delete this service?',
    'vendorDash.editService': 'Edit Service',
    'vendorDash.viewService': 'View Service Details',
    
    // Customer Dashboard additions
    'customerDash.history': 'Booking History',
    'customerDash.historyDesc': 'View your past bookings',
    'customerDash.packages': 'Packages',
    'customerDash.packagesDesc': 'Browse special event packages',
    'customerDash.destinationServices': 'Destination Services',
    'customerDash.destinationServicesDesc': 'Services available at your destination',
  },
  hi: {
    // Navbar
    'nav.listService': 'अपनी सेवा सूचीबद्ध करें',
    'nav.loginRegister': 'लॉगिन/रजिस्टर',
    'nav.logout': 'लॉग आउट',
    'nav.meelova': 'मीलोवा',
    
    // Locations
    'location.gachibowli': 'गचीबौली',
    'location.hiTechCity': 'हाई-टेक सिटी',
    'location.jubileeHills': 'जुबली हिल्स',
    'location.banjaraHills': 'बंजारा हिल्स',
    
    // Hero
    'hero.title': 'आपका कार्यक्रम, परिपूर्ण',
    'hero.subtitle': 'अपने विशेष दिन के लिए सही स्थान और सेवाएं खोजें',
    'hero.getStarted': 'शुरू करें',
    
    // Search
    'search.location': 'स्थान',
    'search.dateTime': 'तारीख और समय',
    'search.topCategories': 'शीर्ष श्रेणियां',
    'search.button': 'खोजें',
    
    // Why Meelova Section
    'whyMeelova.title': 'मीलोवा क्यों?',
    'whyMeelova.description': 'मीलोवा आपके सपनों के कार्यक्रमों और विश्वसनीय सेवा प्रदाताओं के बीच की दूरी को पाटता है। शादी से लेकर कॉर्पोरेट समारोहों तक, हम आपको सत्यापित विक्रेताओं से जोड़ते हैं जो आपकी दृष्टि को जीवंत करते हैं।',
    'whyMeelova.easyDiscovery': 'आसान खोज',
    'whyMeelova.easyDiscoveryDesc': 'अपने कार्यक्रम के लिए सही मैच खोजने के लिए कई श्रेणियों में सैकड़ों सत्यापित विक्रेताओं को ब्राउज़ करें।',
    'whyMeelova.trustedPartners': 'विश्वसनीय साझेदार',
    'whyMeelova.trustedPartnersDesc': 'गुणवत्ता सेवा सुनिश्चित करने के लिए सभी विक्रेता वास्तविक ग्राहकों की वास्तविक रेटिंग और समीक्षाओं के साथ सत्यापित हैं।',
    'whyMeelova.seamlessBooking': 'सहज बुकिंग',
    'whyMeelova.seamlessBookingDesc': 'सेवाओं का अनुरोध करें, बुकिंग की पुष्टि करें और सब कुछ एक ही जगह पर प्रबंधित करें। आपका परिपूर्ण कार्यक्रम बस कुछ क्लिक दूर है।',
    
    // Steps of Process
    'steps.title': 'प्रक्रिया के चरण',
    'steps.signUp': 'साइन अप या लॉग इन करें',
    'steps.signUpDesc': 'शुरू करने के लिए',
    'steps.discover': 'सेवाएं खोजें',
    'steps.discoverDesc': 'अपने कार्यक्रम के लिए',
    'steps.findService': 'सही सेवा खोजें',
    'steps.findServiceDesc': 'प्रदाता और अनुरोध भेजें',
    'steps.confirm': 'प्रदाता से पुष्टि करें,',
    'steps.confirmDesc': 'अग्रिम भुगतान करें',
    'steps.enjoy': 'अंत में, आनंद लें अपना',
    'steps.enjoyDesc': 'परिपूर्ण कार्यक्रम',
    
    // Vendor Statistics
    'vendorStats.title': 'प्रति श्रेणी विक्रेताओं की संख्या',
    'vendorStats.venue': 'स्थान',
    'vendorStats.decorator': 'सजावटकर्ता',
    'vendorStats.photography': 'फोटोग्राफी',
    'vendorStats.djMusic': 'डीजे और संगीत',
    'vendorStats.makeup': 'मेकअप',
    'vendorStats.catering': 'खानपान',
    
    // Event Types
    'events.title': 'कार्यक्रम द्वारा योजना',
    'events.wedding': 'शादी',
    'events.birthday': 'जन्मदिन पार्टी',
    'events.reception': 'रिसेप्शन',
    'events.houseWarming': 'गृह प्रवेश',
    'events.engagement': 'सगाई',
    'events.corporate': 'कॉर्पोरेट कार्यक्रम',
    'events.viewDetails': 'विवरण देखें',
    'events.allEventTypes': 'सभी कार्यक्रम प्रकार',
    'events.browseVendors': 'अपने {event} के लिए विश्वसनीय विक्रेताओं को ब्राउज़ करें और अपने कार्यक्रम को यादगार बनाएं।',
    'events.readyToBook': 'अपना कार्यक्रम बुक करने के लिए तैयार हैं?',
    'events.loginToAccess': 'हमारी पूर्ण विक्रेता सूची तक पहुंचने और अपने परिपूर्ण कार्यक्रम सेवाओं को बुक करने के लिए लॉगिन करें',
    'events.loginToBookServices': 'सेवाएं बुक करने के लिए लॉगिन करें',
    
    // Featured Vendors
    'vendors.title': 'चुनिंदा विक्रेता',
    'vendors.viewAll': 'सभी देखें',
    'vendors.viewDetails': 'विवरण देखें',
    'vendors.loginToBook': 'सेवा बुक करने के लिए लॉगिन करें',
    'vendors.close': 'बंद करें',
    'vendors.about': 'परिचय',
    'vendors.servicesOffered': 'प्रदान की गई सेवाएं',
    'vendors.capacity': 'क्षमता',
    'vendors.priceRange': 'मूल्य सीमा',
    'vendors.amenities': 'सुविधाएं',
    'vendors.loginPrompt': 'इस सेवा को बुक करने के लिए, कृपया अपने खाते में लॉगिन करें',
    
    // Footer
    'footer.tagline': 'आपका कार्यक्रम, परिपूर्ण',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.aboutUs': 'हमारे बारे में',
    'footer.listServices': 'अपनी सेवाएं सूचीबद्ध करें',
    'footer.faqs': 'सामान्य प्रश्न',
    'footer.contactUs': 'संपर्क करें',
    'footer.getInTouch': 'संपर्क में रहें',
    'footer.findService': 'अपनी सेवा खोजें',
    'footer.allRightsReserved': 'सर्वाधिकार सुरक्षित।',
    
    // Search Results (Hindi)
    'search.results': 'खोज परिणाम',
    'search.filters': 'फ़िल्टर',
    'search.found': 'मिले',
    'search.vendors': 'विक्रेता',
    'search.noResults': 'आपकी खोज के अनुसार कोई विक्रेता नहीं मिला',
    'search.backToHome': 'होम पर वापस जाएं',
    'search.category': 'श्रेणी',
    'search.selectDate': 'तारीख़ चुनें',
    'search.selectTime': 'समय चुनें',
    
    // Event Details (Hindi)
    'eventDetails.whatWeOffer': 'हम क्या प्रदान करते हैं',
    'eventDetails.relatedVendors': 'संबंधित विक्रेता',
    
    // Help Center (Hindi)
    'helpCenter.title': 'सहायता केंद्र',
    'helpCenter.placeholder': 'अपना प्रश्न टाइप करें...',
    
    // Vendor Landing
    'vendor.listYour': 'अपनी सूचीबद्ध करें',
    'vendor.onMeelova': 'Meelova.in पर',
    'vendor.tagline': 'मीलोवा भारत का प्रमुख कार्यक्रम बुकिंग प्लेटफ़ॉर्म है जो हर अवसर के लिए ग्राहकों को जोड़ता है।',
    'vendor.registerFree': 'मुफ्त में रजिस्टर करें',
    'vendor.genuineLeads': 'वास्तविक लीड और बुकिंग',
    'vendor.securePayments': 'सुरक्षित और तेज भुगतान',
    'vendor.customerService': '24/7 ग्राहक सेवा',
    'vendor.registerNow': 'अभी रजिस्टर करें',
    'vendor.whyPartner': 'मीलोवा के साथ साझेदारी क्यों करें',
    'vendor.faqs': 'अक्सर पूछे जाने वाले प्रश्न',
    'vendor.faq1': 'कमीशन दरें क्या हैं?',
    'vendor.faq1Answer': 'हम पुष्टि बुकिंग पर 10-15% प्रतिस्पर्धी कमीशन लेते हैं। कोई छिपी फीस या अग्रिम लागत नहीं है।',
    'vendor.faq2': 'मैं विक्रेता के रूप में कैसे शुरू करूं?',
    'vendor.faq2Answer': 'बस "अभी रजिस्टर करें" पर क्लिक करें, अपने व्यवसाय का विवरण भरें, सेवा फोटो अपलोड करें, और अनुमोदन के 24 घंटों के भीतर बुकिंग अनुरोध प्राप्त करना शुरू करें।',
    'vendor.faq3': 'क्या मैं आवश्यकता पड़ने पर बुकिंग रद्द कर सकता हूं?',
    'vendor.faq3Answer': 'हां, आप अपने डैशबोर्ड के माध्यम से बुकिंग रद्द कर सकते हैं। हालांकि, बार-बार रद्दीकरण आपकी रेटिंग और प्लेटफॉर्म पर दृश्यता को प्रभावित कर सकता है।',
    'vendor.faq4': 'मुझे भुगतान कितनी जल्दी मिलता है?',
    'vendor.faq4Answer': 'सफल इवेंट पूर्ण होने के 24-48 घंटों के भीतर भुगतान ट्रांसफर किया जाता है। आप अपने वॉलेट डैशबोर्ड में सभी भुगतान ट्रैक कर सकते हैं।',
    'vendor.faq5': 'आप किस प्रकार का समर्थन प्रदान करते हैं?',
    'vendor.faq5Answer': 'हम फोन, ईमेल और इन-ऐप चैट के माध्यम से 24/7 ग्राहक सहायता प्रदान करते हैं। हमारी समर्पित विक्रेता सफलता टीम ऑनबोर्डिंग, अनुकूलन और किसी भी समस्या को हल करने में मदद करती है।',
    'vendor.faq6': 'क्या मैं एक खाते के तहत कई सेवाएं जोड़ सकता हूं?',
    'vendor.faq6Answer': 'बिल्कुल! आप एक विक्रेता खाते के तहत असीमित सेवाएं सूचीबद्ध कर सकते हैं, खानपान से फोटोग्राफी से सजावट सेवाओं तक।',
    
    // Vendor Landing Page Additional
    'vendor.verifiedLeads': 'सत्यापित लीड',
    'vendor.verifiedLeadsDesc': 'बुक करने के लिए तैयार वास्तविक ग्राहकों से वास्तविक, तुरंत सत्यापित लीड प्राप्त करें।',
    'vendor.instantPayments': 'तुरंत भुगतान',
    'vendor.instantPaymentsDesc': 'तुरंत भुगतान ट्रांसफर—कोई देरी नहीं, कोई प्रतीक्षा नहीं।',
    'vendor.smartDashboard': 'स्मार्ट डैशबोर्ड',
    'vendor.smartDashboardDesc': 'आपकी सभी लीड, बुकिंग और भुगतान एक स्मार्ट डैशबोर्ड में।',
    'vendor.growBusiness': 'अपना व्यवसाय बढ़ाएं',
    'vendor.growBusinessDesc': 'मीलोवा के साथ अपना व्यवसाय बढ़ाएं और अधिक ग्राहकों तक पहुंचें।',
    'vendor.clientChat': 'ग्राहक चैट',
    'vendor.clientChatDesc': 'ग्राहकों के साथ सीधा संवाद।',
    'vendor.howToEnroll': 'अपनी सेवा कैसे नामांकित करें',
    'vendor.getStartedSteps': 'सिर्फ 5 सरल चरणों में शुरू करें',
    'vendor.createAccount': 'खाता बनाएं',
    'vendor.createAccountDesc': 'अपने व्यवसाय के विवरण के साथ साइन अप करें और जल्दी सत्यापित हों',
    'vendor.addServiceDetails': 'सेवा विवरण जोड़ें',
    'vendor.addServiceDetailsDesc': 'उच्च गुणवत्ता वाली फ़ोटो अपलोड करें और अपनी सेवाओं का वर्णन करें',
    'vendor.setPricing': 'मूल्य निर्धारित करें',
    'vendor.setPricingDesc': 'अपनी प्रतिस्पर्धी दरें और उपलब्धता कैलेंडर परिभाषित करें',
    'vendor.getVerified': 'सत्यापित हों',
    'vendor.getVerifiedDesc': 'विश्वास के लिए हमारी त्वरित सत्यापन प्रक्रिया पूर्ण करें',
    'vendor.startReceiving': 'प्राप्त करना शुरू करें',
    'vendor.startReceivingDesc': 'सत्यापित ग्राहकों से तुरंत बुकिंग प्राप्त करें',
    'vendor.securePaymentsTitle': 'सुरक्षित और पारदर्शी भुगतान',
    'vendor.securePaymentsSubtitle': 'उद्योग-अग्रणी सुरक्षा और पारदर्शिता के साथ परेशानी मुक्त भुगतान का अनुभव करें',
    'vendor.instantPayouts': 'तुरंत भुगतान',
    'vendor.instantPayoutsDesc': 'हमारी स्वचालित भुगतान प्रणाली के साथ सेवा पूर्ण होने के तुरंत बाद भुगतान प्राप्त करें।',
    'vendor.earningDashboard': 'आय डैशबोर्ड',
    'vendor.earningDashboardDesc': 'वास्तविक समय में अपनी आय, प्रदर्शन मेट्रिक्स और विकास विश्लेषण ट्रैक करें।',
    'vendor.paymentsMadeEasy': 'भुगतान आसान बनाया',
    'vendor.paymentsMadeEasyDesc': 'आपकी सभी सेवाओं के लिए सहज, तेज़ और आसान भुगतान।',
    'vendor.automatedInvoicing': 'स्वचालित चालान',
    'vendor.automatedInvoicingDesc': 'कर अनुपालन के साथ स्वचालित रूप से उत्पन्न पेशेवर चालान।',
    'vendor.supportedPayments': 'समर्थित भुगतान विधियां',
    'vendor.whatVendorsSay': 'हमारे विक्रेता क्या कहते हैं',
    'vendor.testimonial1': 'इस प्लेटफॉर्म में शामिल होने से मेरे खानपान व्यवसाय में बदलाव आया। सुव्यवस्थित बुकिंग प्रक्रिया और ग्राहक प्रबंधन उपकरणों ने ग्राहकों से जुड़ना आसान बना दिया है, जिससे बुकिंग में वृद्धि हुई है। अत्यधिक अनुशंसित!',
    'vendor.testimonial1Name': 'एमिली जॉनसन',
    'vendor.testimonial1Role': 'गूर्मे डिलाइट्स कैटरिंग की मालिक',
    'vendor.testimonial2': 'एक फोटोग्राफर के रूप में, मुझे ग्राहक खोजने में कठिनाई होती थी। इस प्लेटफॉर्म ने न केवल मुझे इवेंट प्लानर्स से जोड़ा बल्कि मेरी बुकिंग में मूल्यवान जानकारी भी प्रदान की। सपोर्ट टीम शानदार है!',
    'vendor.testimonial2Name': 'माइकल चेन',
    'vendor.testimonial2Role': 'फ्रीलांस फोटोग्राफर',
    'vendor.testimonial3': 'मैं अपनी सजावट सेवाओं को व्यापक दर्शकों के सामने प्रदर्शित करने में सक्षम हुआ। उपयोगकर्ता-अनुकूल इंटरफ़ेस और उत्तरदायी ग्राहक सेवा ने मेरे व्यवसाय की वृद्धि में सारा फर्क डाला है।',
    'vendor.testimonial3Name': 'सोफिया पटेल',
    'vendor.testimonial3Role': 'इवेंट डेकोरेटर',
    'vendor.trustedPartners': 'मीलोवा के विश्वसनीय साझेदार',
    'vendor.faqTitle': 'अक्सर पूछे जाने वाले प्रश्न',
    'vendor.faqSubtitle': 'शुरू करने के बारे में आपको जो कुछ जानना चाहिए',
    'vendor.marketSize': 'बाजार का आकार',
    'vendor.marketValue': 'भारतीय बाजार मूल्य',
    'vendor.eventsPerDay': 'भारत में प्रतिदिन होने वाले कार्यक्रम',
    'vendor.projected': 'अनुमानित (2025–2028)',
    'vendor.footerTagline': 'विक्रेताओं को ग्राहकों से जोड़ने वाला भारत का सबसे बड़ा इवेंट और मनोरंजन प्रबंधन प्लेटफॉर्म। सत्यापित लीड और सुरक्षित भुगतान के साथ अपना व्यवसाय बनाएं।',
    'vendor.contactUs': 'हमसे संपर्क करें',
    'vendor.copyright': '© 2025 मीलोवा। सर्वाधिकार सुरक्षित।',
    'vendor.venue': 'स्थान',
    'vendor.djSound': 'डीजे साउंड',
    'vendor.cateringService': 'खानपान',
    'vendor.photography': 'फोटोग्राफी',
    'vendor.decorationService': 'सजावट',
    'vendor.musicBand': 'म्यूजिक बैंड',
    
    // Dashboard
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.bookings': 'बुकिंग',
    'dashboard.myServices': 'मेरी सेवाएं',
    'dashboard.addService': 'नई सेवा जोड़ें',
    'dashboard.wallet': 'वॉलेट',
    'dashboard.messages': 'संदेश',
    'dashboard.settings': 'सेटिंग्स',
    'dashboard.eAlbum': 'ई-एलबम',
    
    // Login
    'login.title': 'वापस स्वागत है',
    'login.subtitle': 'अपने मीलोवा खाते में लॉगिन करें',
    'login.email': 'ईमेल',
    'login.password': 'पासवर्ड',
    'login.button': 'लॉगिन',
    'login.noAccount': 'खाता नहीं है?',
    'login.signupLink': 'साइन अप करें',
    
    // Signup
    'signup.title': 'खाता बनाएं',
    'signup.subtitle': 'आज मीलोवा में शामिल हों',
    'signup.name': 'पूरा नाम',
    'signup.email': 'ईमेल',
    'signup.password': 'पासवर्ड',
    'signup.button': 'साइन अप',
    'signup.hasAccount': 'पहले से खाता है?',
    'signup.loginLink': 'लॉगिन',
    
    // Vendor Registration
    'vendorReg.title': 'विक्रेता पंजीकरण',
    'vendorReg.profile': 'प्रोफाइल',
    'vendorReg.documents': 'दस्तावेज़',
    'vendorReg.portfolio': 'पोर्टफोलियो',
    'vendorReg.pricing': 'मूल्य निर्धारण',
    'vendorReg.step': 'चरण',
    'vendorReg.businessName': 'व्यवसाय का नाम',
    'vendorReg.ownerName': 'मालिक का नाम',
    'vendorReg.phone': 'फोन नंबर',
    'vendorReg.category': 'सेवा श्रेणी',
    'vendorReg.address': 'व्यवसाय का पता',
    'vendorReg.description': 'व्यवसाय विवरण',
    'vendorReg.previous': 'पिछला',
    'vendorReg.next': 'अगला',
    'vendorReg.goToDashboard': 'डैशबोर्ड पर जाएं',
    'vendorReg.panCard': 'पैन कार्ड',
    'vendorReg.aadhaarCard': 'आधार कार्ड',
    'vendorReg.gstCertificate': 'जीएसटी प्रमाणपत्र (यदि लागू हो)',
    'vendorReg.businessLicense': 'व्यवसाय लाइसेंस/पंजीकरण',
    'vendorReg.bankProof': 'बैंक खाता प्रमाण',
    'vendorReg.workImages': 'कार्य प्रदर्शन छवियां',
    'vendorReg.certificates': 'प्रमाणपत्र और पुरस्कार',
    'vendorReg.workHistory': 'कार्य इतिहास',
    'vendorReg.socialMedia': 'सोशल मीडिया लिंक',
    'vendorReg.serviceName': 'सेवा का नाम',
    'vendorReg.basePrice': 'आधार मूल्य (₹)',
    'vendorReg.capacity': 'क्षमता',
    'vendorReg.pricingDescription': 'मूल्य निर्धारण विवरण',
    'vendorReg.advancePayment': 'अग्रिम भुगतान आवश्यक (%)',
    'vendorReg.cancellationPolicy': 'रद्दीकरण नीति',
    'vendorReg.availability': 'उपलब्धता',
    'vendorReg.uploadPan': 'पैन कार्ड की स्पष्ट प्रति अपलोड करें',
    'vendorReg.uploadAadhaar': 'आधार के आगे और पीछे अपलोड करें',
    'vendorReg.uploadGst': 'जीएसटी पंजीकरण प्रमाणपत्र अपलोड करें',
    'vendorReg.uploadBusinessDoc': 'कोई भी व्यवसाय पंजीकरण दस्तावेज',
    'vendorReg.uploadBankProof': 'रद्द चेक या बैंक स्टेटमेंट',
    'vendorReg.uploadWorkImages': 'अपने काम की कम से कम 5 उच्च गुणवत्ता वाली छवियां अपलोड करें (अधिकतम 20 छवियां)',
    'vendorReg.uploadCertificates': 'कोई भी पुरस्कार, प्रमाणपत्र, या उपलब्धियां',
    'vendorReg.workHistoryPlaceholder': 'अपने अनुभव, उल्लेखनीय कार्यक्रम, ग्राहकों का वर्णन करें...',
    'vendorReg.instagramPlaceholder': 'इंस्टाग्राम प्रोफाइल URL',
    'vendorReg.facebookPlaceholder': 'फेसबुक पेज URL',
    'vendorReg.websitePlaceholder': 'वेबसाइट URL (यदि कोई हो)',
    'vendorReg.serviceNamePlaceholder': 'उदाहरण: मूल पैकेज, प्रीमियम पैकेज',
    'vendorReg.basePricePlaceholder': '50000',
    'vendorReg.capacityPlaceholder': '200 व्यक्ति',
    'vendorReg.pricingDescPlaceholder': 'इस कीमत में क्या शामिल है? कोई अतिरिक्त शुल्क?',
    'vendorReg.advancePaymentPlaceholder': '30',
    'vendorReg.advancePaymentHelper': 'बुकिंग के लिए आवश्यक अग्रिम भुगतान का प्रतिशत',
    'vendorReg.cancellationPlaceholder': 'अपनी रद्दीकरण और रिफंड नीति का वर्णन करें',
    'vendorReg.availabilityPlaceholder': 'आपके कार्य दिवस, घंटे, ब्लैकआउट तिथियां...',
    'vendorReg.registrationComplete': 'पंजीकरण पूर्ण!',
    'vendorReg.registrationSuccess': 'आपका विक्रेता खाता सफलतापूर्वक बनाया गया है।',
    
    // Vendor Dashboard
    'vendorDash.title': 'विक्रेता डैशबोर्ड',
    'vendorDash.dashboard': 'डैशबोर्ड',
    'vendorDash.bookings': 'बुकिंग',
    'vendorDash.services': 'मेरी सेवाएं',
    'vendorDash.addService': 'नई सेवा जोड़ें',
    'vendorDash.wallet': 'वॉलेट',
    'vendorDash.messages': 'संदेश',
    'vendorDash.settings': 'सेटिंग्स',
    'vendorDash.profile': 'प्रोफाइल',
    'vendorDash.logout': 'लॉग आउट',
    'vendorDash.totalEarnings': 'कुल कमाई',
    'vendorDash.activeBookings': 'सक्रिय बुकिंग',
    'vendorDash.totalClients': 'कुल ग्राहक',
    'vendorDash.pendingRequests': 'लंबित अनुरोध',
    'vendorDash.fromLastMonth': 'पिछले महीने से +20%',
    'vendorDash.fromLastWeek': 'पिछले सप्ताह से +3',
    'vendorDash.newThisMonth': 'इस महीने +8 नए',
    'vendorDash.respondQuickly': 'जल्दी जवाब दें',
    'vendorDash.earningsOverview': 'कमाई का अवलोकन',
    'vendorDash.earningsOverviewDesc': 'पिछले 6 महीनों की आपकी मासिक कमाई',
    'vendorDash.quickActions': 'त्वरित कार्य',
    'vendorDash.addNewService': 'नई सेवा जोड़ें',
    'vendorDash.viewBookings': 'बुकिंग देखें',
    'vendorDash.checkMessages': 'संदेश देखें',
    'vendorDash.myBookings': 'मेरी बुकिंग',
    'vendorDash.myBookingsDesc': 'अपनी आगामी और पिछली बुकिंग प्रबंधित करें',
    'vendorDash.weddingReception': 'शादी का रिसेप्शन',
    'vendorDash.bookingDate': 'तारीख: 25 दिसंबर 2025 | ग्राहक: जॉन डो',
    'vendorDash.viewDetailsBtn': 'विवरण देखें',
    'vendorDash.myServicesTitle': 'मेरी सेवाएं',
    'vendorDash.myServicesDesc': 'प्लेटफॉर्म पर आपकी सूचीबद्ध सेवाएं',
    'vendorDash.status': 'स्थिति',
    'vendorDash.active': 'सक्रिय',
    'vendorDash.edit': 'संपादित करें',
    'vendorDash.view': 'देखें',
    'vendorDash.addServiceTitle': 'नई सेवा जोड़ें',
    'vendorDash.addServiceDesc': 'प्लेटफॉर्म पर नई सेवा सूचीबद्ध करें',
    'vendorDash.serviceName': 'सेवा का नाम',
    'vendorDash.serviceNamePlaceholder': 'उदा., शादी की फोटोग्राफी',
    'vendorDash.serviceDescription': 'विवरण',
    'vendorDash.serviceDescPlaceholder': 'अपनी सेवा का वर्णन करें...',
    'vendorDash.price': 'मूल्य (₹)',
    'vendorDash.serviceImages': 'सेवा छवियां',
    'vendorDash.clickToUpload': 'छवियां अपलोड करने के लिए क्लिक करें',
    'vendorDash.uploadLimit': 'PNG, JPG 10MB तक',
    'vendorDash.addServiceBtn': 'सेवा जोड़ें',
    'vendorDash.walletTitle': 'वॉलेट',
    'vendorDash.walletDesc': 'अपनी कमाई और भुगतान प्रबंधित करें',
    'vendorDash.availableBalance': 'उपलब्ध शेष',
    'vendorDash.withdrawFunds': 'धन निकालें',
    'vendorDash.recentTransactions': 'हाल के लेनदेन',
    'vendorDash.paymentReceived': 'भुगतान प्राप्त',
    'vendorDash.messagesTitle': 'संदेश',
    'vendorDash.messagesDesc': 'अपने ग्राहकों से चैट करें',
    'vendorDash.client': 'ग्राहक',
    'vendorDash.lastMessagePreview': 'अंतिम संदेश पूर्वावलोकन...',
    'vendorDash.hoursAgo': '2 घंटे पहले',
    'vendorDash.profileSettings': 'प्रोफाइल सेटिंग्स',
    'vendorDash.businessName': 'व्यवसाय का नाम',
    'vendorDash.businessNamePlaceholder': 'आपका व्यवसाय नाम',
    'vendorDash.email': 'ईमेल',
    'vendorDash.emailPlaceholder': 'your@email.com',
    'vendorDash.phone': 'फोन',
    'vendorDash.phonePlaceholder': '+91 9876543210',
    'vendorDash.updateProfile': 'प्रोफाइल अपडेट करें',
    'vendorDash.language': 'भाषा',
    'vendorDash.selectLanguage': 'भाषा चुनें',
    'vendorDash.notifications': 'सूचनाएं',
    'vendorDash.emailNotifications': 'ईमेल सूचनाएं',
    'vendorDash.smsNotifications': 'एसएमएस सूचनाएं',
    'vendorDash.bookingAlerts': 'बुकिंग अलर्ट',
    'vendorDash.weddingPhotography': 'शादी की फोटोग्राफी',
    'vendorDash.birthdayDecoration': 'जन्मदिन सजावट',
    'vendorDash.corporateEventCatering': 'कॉर्पोरेट इवेंट खानपान',
    
    // Customer Dashboard
    'customerDash.filterBy': 'फ़िल्टर करें',
    'customerDash.eventType': 'कार्यक्रम प्रकार',
    'customerDash.wedding': 'शादी',
    'customerDash.reception': 'रिसेप्शन',
    'customerDash.birthdayParty': 'जन्मदिन पार्टी',
    'customerDash.ceremonies': 'समारोह',
    'customerDash.anniversaries': 'सालगिरह',
    'customerDash.privateParties': 'निजी पार्टियां',
    'customerDash.priceRange': 'मूल्य सीमा',
    'customerDash.dateTime': 'तारीख और समय',
    'customerDash.amenitiesFeatures': 'सुविधाएं और विशेषताएं',
    'customerDash.discoverVenue': 'अपना सही स्थान खोजें',
    'customerDash.viewDetails': 'विवरण देखें',
    'customerDash.requestService': 'सेवा अनुरोध',
    'customerDash.logout': 'लॉग आउट',
    'customerDash.perfectFor': 'छोटी पार्टियों के लिए बिल्कुल सही',
    'customerDash.ac': 'एयर कंडीशनिंग',
    'customerDash.parking': 'पार्किंग',
    'customerDash.catering': 'खानपान',
    'customerDash.wifi': 'वाईफाई',
    'customerDash.sound': 'साउंड सिस्टम',
    'customerDash.decoration': 'सजावट',
    'customerDash.close': 'बंद करें',
    'customerDash.about': 'परिचय',
    'customerDash.servicesOffered': 'प्रदान की गई सेवाएं',
    'customerDash.capacity': 'क्षमता',
    'customerDash.priceRangeLabel': 'मूल्य सीमा',
    'customerDash.amenities': 'सुविधाएं',
    'customerDash.bookNow': 'अभी बुक करें',
    'customerDash.guests': 'मेहमान',
    'customerDash.meelova': 'Meelova',
    'customerDash.meelovaHi': 'मीलोवा',
    'customerDash.meelovaTe': 'మీలోవా',
    'customerDash.confirmBooking': 'बुकिंग की पुष्टि करें',
    'customerDash.requestSent': 'आपका अनुरोध भेज दिया गया है!',
    'customerDash.waitForStatus': 'कृपया विक्रेता द्वारा आपकी बुकिंग की पुष्टि की प्रतीक्षा करें। स्थिति अपडेट होने पर आपको सूचना मिलेगी।',
    'customerDash.okGotIt': 'ठीक है, समझ गया',
    'customerDash.cancel': 'रद्द करें',
    'customerDash.lights': 'लाइट्स',
    'customerDash.stage': 'स्टेज सेटअप',
    'customerDash.floralDecor': 'फूलों की सजावट',
    'customerDash.videoScreen': 'वीडियो स्क्रीन',
    
    // Vendor data translations
    'vendor.royalPalace': 'रॉयल पैलेस बैंक्वेट हॉल',
    'vendor.royalPalaceDesc': 'आपके विशेष क्षणों के लिए असाधारण सेवा',
    'vendor.royalPalaceFull': 'रॉयल पैलेस बैंक्वेट हॉल शादियों, रिसेप्शन और कॉर्पोरेट कार्यक्रमों के लिए विश्व स्तरीय सुविधाएं प्रदान करने वाला प्रीमियम स्थान है। 500+ मेहमानों की क्षमता, सुरुचिपूर्ण सजावट और आधुनिक सुविधाओं के साथ जिसमें सेंट्रल एसी, एलईडी लाइटिंग और पेशेवर साउंड सिस्टम शामिल हैं।',
    'vendor.grandHeritage': 'ग्रैंड हेरिटेज वेडिंग वेन्यू',
    'vendor.grandHeritageDesc': 'आपके विशेष क्षणों के लिए असाधारण सेवा',
    'vendor.grandHeritageFull': 'ग्रैंड हेरिटेज आधुनिक सुविधाओं के साथ पारंपरिक सुंदरता लाता है। अंतरंग शादियों और भव्य रिसेप्शन के लिए बिल्कुल सही। हमारी अनुभवी टीम आपके विशेष दिन के लिए हर विवरण को परिपूर्ण बनाती है।',
    'vendor.premiumGarden': 'प्रीमियम गार्डन इवेंट्स',
    'vendor.premiumGardenDesc': 'आपके विशेष क्षणों के लिए असाधारण सेवा',
    'vendor.premiumGardenFull': 'प्रीमियम गार्डन इवेंट्स सुंदर रूप से सजाए गए बगीचों में आउटडोर समारोहों में विशेषज्ञ है। दिन की शादियों, जन्मदिन पार्टियों और प्राकृतिक माहौल के साथ थीम आधारित कार्यक्रमों के लिए आदर्श।',
    'vendor.weddingVenue': 'शादी का स्थान',
    'vendor.receptionHall': 'रिसेप्शन हॉल',
    'vendor.corporateEvents': 'कॉर्पोरेट कार्यक्रम',
    'vendor.weddingService': 'शादी',
    'vendor.engagementService': 'सगाई',
    'vendor.receptionService': 'रिसेप्शन',
    'vendor.outdoorEvents': 'आउटडोर कार्यक्रम',
    'vendor.gardenWeddings': 'गार्डन वेडिंग',
    'vendor.birthdayParties': 'जन्मदिन पार्टियां',
    'vendor.centralAc': 'सेंट्रल एसी',
    'vendor.ledLighting': 'एलईडी लाइटिंग',
    'vendor.soundSystem': 'साउंड सिस्टम',
    'vendor.parkingAvailable': 'पार्किंग',
    'vendor.cateringAvailable': 'खानपान उपलब्ध',
    'vendor.gardenArea': 'गार्डन क्षेत्र',
    'vendor.decorativeLighting': 'सजावटी लाइटिंग',
    'vendor.inHouseCatering': 'इन-हाउस खानपान',
    'vendor.valetParking': 'वैलेट पार्किंग',
    'vendor.bridalRoom': 'ब्राइडल रूम',
    'vendor.landscapedGarden': 'सजा हुआ बगीचा',
    'vendor.outdoorLighting': 'आउटडोर लाइटिंग',
    'vendor.gazebo': 'गजीबो',
    'vendor.amplePar': 'पर्याप्त पार्किंग',
    'vendor.flexibleCatering': 'लचीला खानपान',
    'vendor.cashfree': 'कैशफ्री',
    'vendor.upi': 'यूपीआई',
    'vendor.cards': 'कार्ड्स',
    
    // Vendor Dashboard History & Calendar
    'vendorDash.history': 'इतिहास',
    'vendorDash.historyDesc': 'अपनी पिछली बुकिंग और लेनदेन देखें',
    'vendorDash.calendar': 'कैलेंडर',
    'vendorDash.calendarDesc': 'अपने निर्धारित कार्यक्रम देखें',
    'vendorDash.cashOnSpot': 'स्पॉट पर नकद',
    'vendorDash.currentTransactions': 'वर्तमान लेनदेन',
    'vendorDash.noEventsToday': 'इस तारीख के लिए कोई कार्यक्रम निर्धारित नहीं है',
    'vendorDash.completed': 'पूर्ण',
    'vendorDash.pending': 'लंबित',
    'vendorDash.serviceUpdated': 'सेवा सफलतापूर्वक अपडेट की गई',
    'vendorDash.serviceDeleted': 'सेवा सफलतापूर्वक हटा दी गई',
    'vendorDash.confirmDelete': 'क्या आप वाकई इस सेवा को हटाना चाहते हैं?',
    'vendorDash.editService': 'सेवा संपादित करें',
    'vendorDash.viewService': 'सेवा विवरण देखें',
    
    // Customer Dashboard additions
    'customerDash.history': 'बुकिंग इतिहास',
    'customerDash.historyDesc': 'अपनी पिछली बुकिंग देखें',
    'customerDash.packages': 'पैकेज',
    'customerDash.packagesDesc': 'विशेष इवेंट पैकेज ब्राउज़ करें',
    'customerDash.destinationServices': 'गंतव्य सेवाएं',
    'customerDash.destinationServicesDesc': 'आपके गंतव्य पर उपलब्ध सेवाएं',
  },
  te: {
    // Navbar
    'nav.listService': 'మీ సేవను జాబితా చేయండి',
    'nav.loginRegister': 'లాగిన్/రిజిస్టర్',
    'nav.logout': 'లాగ్ అవుట్',
    'nav.meelova': 'మీలోవా',
    
    // Locations
    'location.gachibowli': 'గచ్చిబౌలి',
    'location.hiTechCity': 'హై-టెక్ సిటీ',
    'location.jubileeHills': 'జూబ్లీ హిల్స్',
    'location.banjaraHills': 'బంజారా హిల్స్',
    
    // Hero
    'hero.title': 'మీ ఈవెంట్, పరిపూర్ణం',
    'hero.subtitle': 'మీ ప్రత్యేక రోజు కోసం సరైన వేదిక మరియు సేవలను కనుగొనండి',
    'hero.getStarted': 'ప్రారంభించండి',
    
    // Search
    'search.location': 'స్థలం',
    'search.dateTime': 'తేదీ & సమయం',
    'search.topCategories': 'టాప్ వర్గాలు',
    'search.button': 'వెతకండి',
    
    // Why Meelova Section
    'whyMeelova.title': 'మీలోవా ఎందుకు?',
    'whyMeelova.description': 'మీలోవా మీ కలల ఈవెంట్‌లు మరియు విశ్వసనీయ సేవా ప్రదాతల మధ్య అంతరాన్ని తగ్గిస్తుంది. పెళ్లిళ్ల నుండి కార్పొరేట్ సమావేశాల వరకు, మీ దృష్టిని జీవంలోకి తీసుకువచ్చే ధృవీకరించబడిన విక్రేతలతో మిమ్మల్ని కనెక్ట్ చేస్తాము.',
    'whyMeelova.easyDiscovery': 'సులభ ఆవిష్కరణ',
    'whyMeelova.easyDiscoveryDesc': 'మీ ఈవెంట్‌కు సరైన జతను కనుగొనడానికి బహుళ వర్గాలలో వందలాది ధృవీకరించబడిన విక్రేతలను బ్రౌజ్ చేయండి.',
    'whyMeelova.trustedPartners': 'విశ్వసనీయ భాగస్వాములు',
    'whyMeelova.trustedPartnersDesc': 'నాణ్యత సేవను నిర్ధారించడానికి అన్ని విక్రేతలు నిజమైన కస్టమర్ల నిజమైన రేటింగ్‌లు మరియు సమీక్షలతో ధృవీకరించబడ్డారు.',
    'whyMeelova.seamlessBooking': 'సులభ బుకింగ్',
    'whyMeelova.seamlessBookingDesc': 'సేవలను అభ్యర్థించండి, బుకింగ్‌లను నిర్ధారించండి మరియు అన్నింటినీ ఒకే చోట నిర్వహించండి. మీ పరిపూర్ణ ఈవెంట్ కొన్ని క్లిక్‌ల దూరంలో ఉంది.',
    
    // Steps of Process
    'steps.title': 'ప్రక్రియ దశలు',
    'steps.signUp': 'సైన్ అప్ లేదా లాగిన్ చేయండి',
    'steps.signUpDesc': 'ప్రారంభించడానికి',
    'steps.discover': 'సేవలను కనుగొనండి',
    'steps.discoverDesc': 'మీ ఈవెంట్ కోసం',
    'steps.findService': 'సరైన సేవను కనుగొనండి',
    'steps.findServiceDesc': 'ప్రొవైడర్ మరియు అభ్యర్థన పంపండి',
    'steps.confirm': 'ప్రొవైడర్‌తో నిర్ధారించండి,',
    'steps.confirmDesc': 'అడ్వాన్స్ చెల్లించండి',
    'steps.enjoy': 'చివరగా, ఆనందించండి మీ',
    'steps.enjoyDesc': 'పరిపూర్ణ ఈవెంట్',
    
    // Vendor Statistics
    'vendorStats.title': 'వర్గం వారీగా విక్రేతల సంఖ్య',
    'vendorStats.venue': 'వేదిక',
    'vendorStats.decorator': 'డెకొరేటర్',
    'vendorStats.photography': 'ఫోటోగ్రఫీ',
    'vendorStats.djMusic': 'DJ & సంగీతం',
    'vendorStats.makeup': 'మేకప్',
    'vendorStats.catering': 'క్యాటరింగ్',
    
    // Event Types
    'events.title': 'ఈవెంట్ ద్వారా ప్రణాళిక',
    'events.wedding': 'పెళ్లి',
    'events.birthday': 'పుట్టినరోజు పార్టీ',
    'events.reception': 'రిసెప్షన్',
    'events.houseWarming': 'గృహప్రవేశం',
    'events.engagement': 'నిశ్చితార్థం',
    'events.corporate': 'కార్పొరేట్ ఈవెంట్',
    'events.viewDetails': 'వివరాలు చూడండి',
    'events.allEventTypes': 'అన్ని ఈవెంట్ రకాలు',
    'events.browseVendors': 'మీ {event} కోసం విశ్వసనీయ విక్రేతలను బ్రౌజ్ చేయండి మరియు మీ ఈవెంట్‌ను గుర్తుండిపోయేలా చేయండి.',
    'events.readyToBook': 'మీ ఈవెంట్‌ను బుక్ చేయడానికి సిద్ధంగా ఉన్నారా?',
    'events.loginToAccess': 'మా పూర్తి విక్రేత జాబితాను యాక్సెస్ చేయడానికి మరియు మీ పరిపూర్ణ ఈవెంట్ సేవలను బుక్ చేయడానికి లాగిన్ అవ్వండి',
    'events.loginToBookServices': 'సేవలను బుక్ చేయడానికి లాగిన్ అవ్వండి',
    
    // Featured Vendors
    'vendors.title': 'ఫీచర్డ్ విక్రేతలు',
    'vendors.viewAll': 'అన్నీ చూడండి',
    'vendors.viewDetails': 'వివరాలు చూడండి',
    'vendors.loginToBook': 'సేవను బుక్ చేయడానికి లాగిన్ చేయండి',
    'vendors.close': 'మూసివేయండి',
    'vendors.about': 'గురించి',
    'vendors.servicesOffered': 'అందించే సేవలు',
    'vendors.capacity': 'సామర్థ్యం',
    'vendors.priceRange': 'ధర పరిధి',
    'vendors.amenities': 'సౌకర్యాలు',
    'vendors.loginPrompt': 'ఈ సేవను బుక్ చేయడానికి, దయచేసి మీ ఖాతాకు లాగిన్ అవ్వండి',
    
    // Footer
    'footer.tagline': 'మీ ఈవెంట్, పరిపూర్ణం',
    'footer.quickLinks': 'శీఘ్ర లింక్‌లు',
    'footer.aboutUs': 'మా గురించి',
    'footer.listServices': 'మీ సేవలను జాబితా చేయండి',
    'footer.faqs': 'తరచుగా అడిగే ప్రశ్నలు',
    'footer.contactUs': 'మమ్మల్ని సంప్రదించండి',
    'footer.getInTouch': 'సంప్రదించండి',
    'footer.findService': 'మీ సేవను కనుగొనండి',
    'footer.allRightsReserved': 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    
    // Search Results (Telugu)
    'search.results': 'శోధన ఫలితాలు',
    'search.filters': 'ఫిల్టర్లు',
    'search.found': 'కనుగొనబడింది',
    'search.vendors': 'విక్రేతలు',
    'search.noResults': 'మీ శోధనకు సరిపోయే విక్రేతలు కనుగొనబడలేదు',
    'search.backToHome': 'హోమ్‌కు తిరిగి వెళ్ళండి',
    'search.category': 'వర్గం',
    'search.selectDate': 'తేదీ ఎంచుకోండి',
    'search.selectTime': 'సమయం ఎంచుకోండి',
    
    // Event Details (Telugu)
    'eventDetails.whatWeOffer': 'మేము ఏమి అందిస్తాము',
    'eventDetails.relatedVendors': 'సంబంధిత విక్రేతలు',
    
    // Help Center (Telugu)
    'helpCenter.title': 'సహాయ కేంద్రం',
    'helpCenter.placeholder': 'మీ ప్రశ్న టైప్ చేయండి...',
    
    // Vendor Landing
    'vendor.listYour': 'మీ జాబితా చేయండి',
    'vendor.onMeelova': 'Meelova.in లో',
    'vendor.tagline': 'మీలోవా భారతదేశం యొక్క ప్రీమియర్ ఈవెంట్ బుకింగ్ ప్లాట్‌ఫారమ్, ప్రతి సందర్భానికి క్లయింట్‌లను కనెక్ట్ చేస్తుంది.',
    'vendor.registerFree': 'ఉచితంగా రిజిస్టర్ చేయండి',
    'vendor.genuineLeads': 'నిజమైన లీడ్స్ మరియు బుకింగ్',
    'vendor.securePayments': 'సురక్షిత మరియు వేగవంతమైన చెల్లింపులు',
    'vendor.customerService': '24/7 కస్టమర్ సేవ',
    'vendor.registerNow': 'ఇప్పుడే రిజిస్టర్ చేయండి',
    'vendor.whyPartner': 'మీలోవాతో భాగస్వామ్యం ఎందుకు',
    'vendor.faqs': 'తరచుగా అడిగే ప్రశ్నలు',
    'vendor.faq1': 'కమీషన్ రేట్లు ఏమిటి?',
    'vendor.faq1Answer': 'మేము ధృవీకరించిన బుకింగ్‌లపై పోటీ 10-15% కమీషన్ వసూలు చేస్తాము. దాచిన ఫీజులు లేదా ముందస్తు ఖర్చులు లేవు.',
    'vendor.faq2': 'నేను విక్రేతగా ఎలా ప్రారంభించాలి?',
    'vendor.faq2Answer': 'కేవలం "ఇప్పుడే రిజిస్టర్ చేయండి" పై క్లిక్ చేయండి, మీ వ్యాపార వివరాలను పూరించండి, సేవా ఫోటోలను అప్‌లోడ్ చేయండి, మరియు ఆమోదం పొందిన 24 గంటల్లో బుకింగ్ అభ్యర్థనలను స్వీకరించడం ప్రారంభించండి.',
    'vendor.faq3': 'అవసరమైతే నేను బుకింగ్‌లను రద్దు చేయవచ్చా?',
    'vendor.faq3Answer': 'అవును, మీరు మీ డాష్‌బోర్డ్ ద్వారా బుకింగ్‌లను రద్దు చేయవచ్చు. అయితే, పునరావృత రద్దులు ప్లాట్‌ఫారమ్‌లో మీ రేటింగ్‌లు మరియు దృశ్యమానతను ప్రభావితం చేయవచ్చు.',
    'vendor.faq4': 'నాకు చెల్లింపులు ఎంత త్వరగా వస్తాయి?',
    'vendor.faq4Answer': 'విజయవంతమైన ఈవెంట్ పూర్తయిన 24-48 గంటల్లో చెల్లింపులు బదిలీ చేయబడతాయి. మీరు మీ వాలెట్ డ్యాష్‌బోర్డ్‌లో అన్ని చెల్లింపులను ట్రాక్ చేయవచ్చు.',
    'vendor.faq5': 'మీరు ఏ రకమైన మద్దతు అందిస్తారు?',
    'vendor.faq5Answer': 'మేము ఫోన్, ఇమెయిల్ మరియు ఇన్-యాప్ చాట్ ద్వారా 24/7 కస్టమర్ సపోర్ట్ అందిస్తాము. మా అంకితమైన విక్రేత విజయ బృందం ఆన్‌బోర్డింగ్, ఆప్టిమైజేషన్ మరియు ఏవైనా సమస్యలను పరిష్కరించడంలో సహాయపడుతుంది.',
    'vendor.faq6': 'నేను ఒక ఖాతా క్రింద బహుళ సేవలను జోడించగలనా?',
    'vendor.faq6Answer': 'ఖచ్చితంగా! మీరు ఒక విక్రేత ఖాతా క్రింద అపరిమిత సేవలను జాబితా చేయవచ్చు, క్యాటరింగ్ నుండి ఫోటోగ్రఫీ నుండి డెకొరేషన్ సేవల వరకు.',
    
    // Vendor Landing Page Additional
    'vendor.verifiedLeads': 'ధృవీకరించిన లీడ్స్',
    'vendor.verifiedLeadsDesc': 'బుక్ చేయడానికి సిద్ధంగా ఉన్న నిజమైన క్లయింట్‌ల నుండి నిజమైన, తక్షణ ధృవీకరించిన లీడ్‌లను పొందండి.',
    'vendor.instantPayments': 'తక్షణ చెల్లింపులు',
    'vendor.instantPaymentsDesc': 'తక్షణ చెల్లింపు బదిలీలు—ఆలస్యం లేదు, వేచి ఉండటం లేదు.',
    'vendor.smartDashboard': 'స్మార్ట్ డ్యాష్‌బోర్డ్',
    'vendor.smartDashboardDesc': 'మీ అన్ని లీడ్‌లు, బుకింగ్‌లు మరియు చెల్లింపులు ఒక స్మార్ట్ డ్యాష్‌బోర్డ్‌లో.',
    'vendor.growBusiness': 'మీ వ్యాపారాన్ని పెంచుకోండి',
    'vendor.growBusinessDesc': 'మీలోవాతో మీ వ్యాపారాన్ని పెంచుకోండి మరియు ఎక్కువ క్లయింట్‌లను చేరుకోండి.',
    'vendor.clientChat': 'క్లయింట్ చాట్',
    'vendor.clientChatDesc': 'క్లయింట్‌లతో ప్రత్యక్ష కమ్యూనికేషన్.',
    'vendor.howToEnroll': 'మీ సేవను ఎలా నమోదు చేయాలి',
    'vendor.getStartedSteps': 'కేవలం 5 సులభ దశల్లో ప్రారంభించండి',
    'vendor.createAccount': 'ఖాతా సృష్టించండి',
    'vendor.createAccountDesc': 'మీ వ్యాపార వివరాలతో సైన్ అప్ చేయండి మరియు త్వరగా ధృవీకరించబడండి',
    'vendor.addServiceDetails': 'సేవా వివరాలను జోడించండి',
    'vendor.addServiceDetailsDesc': 'అధిక నాణ్యత ఫోటోలను అప్‌లోడ్ చేయండి మరియు మీ సేవలను వివరించండి',
    'vendor.setPricing': 'ధరను సెట్ చేయండి',
    'vendor.setPricingDesc': 'మీ పోటీ రేట్లు మరియు లభ్యత క్యాలెండర్‌ను నిర్వచించండి',
    'vendor.getVerified': 'ధృవీకరించబడండి',
    'vendor.getVerifiedDesc': 'విశ్వాసం కోసం మా త్వరిత ధృవీకరణ ప్రక్రియను పూర్తి చేయండి',
    'vendor.startReceiving': 'స్వీకరించడం ప్రారంభించండి',
    'vendor.startReceivingDesc': 'ధృవీకరించిన క్లయింట్‌ల నుండి వెంటనే బుకింగ్‌లను పొందండి',
    'vendor.securePaymentsTitle': 'సురక్షిత మరియు పారదర్శక చెల్లింపులు',
    'vendor.securePaymentsSubtitle': 'పరిశ్రమ-అగ్రగామి భద్రత మరియు పారదర్శకతతో సమస్య-రహిత చెల్లింపులను అనుభవించండి',
    'vendor.instantPayouts': 'తక్షణ చెల్లింపులు',
    'vendor.instantPayoutsDesc': 'మా ఆటోమేటెడ్ పేమెంట్ సిస్టమ్‌తో సేవ పూర్తయిన వెంటనే చెల్లింపు పొందండి.',
    'vendor.earningDashboard': 'ఆదాయ డ్యాష్‌బోర్డ్',
    'vendor.earningDashboardDesc': 'రియల్-టైమ్‌లో మీ ఆదాయం, పనితీరు మెట్రిక్‌లు మరియు వృద్ధి విశ్లేషణలను ట్రాక్ చేయండి.',
    'vendor.paymentsMadeEasy': 'చెల్లింపులు సులభం చేయబడ్డాయి',
    'vendor.paymentsMadeEasyDesc': 'మీ అన్ని సేవల కోసం సులభమైన, వేగవంతమైన మరియు సులువైన చెల్లింపులు.',
    'vendor.automatedInvoicing': 'ఆటోమేటెడ్ ఇన్వాయిసింగ్',
    'vendor.automatedInvoicingDesc': 'పన్ను సమ్మతితో స్వయంచాలకంగా రూపొందించబడిన ప్రొఫెషనల్ ఇన్వాయిస్‌లు.',
    'vendor.supportedPayments': 'సపోర్టెడ్ పేమెంట్ మెథడ్స్',
    'vendor.whatVendorsSay': 'మా విక్రేతలు ఏమి చెబుతున్నారు',
    'vendor.testimonial1': 'ఈ ప్లాట్‌ఫారమ్‌లో చేరడం నా క్యాటరింగ్ వ్యాపారాన్ని మార్చివేసింది. సరళీకృత బుకింగ్ ప్రక్రియ మరియు క్లయింట్ మేనేజ్‌మెంట్ టూల్స్ క్లయింట్‌లతో కనెక్ట్ అవ్వడాన్ని సులభతరం చేశాయి, బుకింగ్‌లలో పెరుగుదలకు దారితీశాయి. అత్యధికంగా సిఫార్సు చేయబడింది!',
    'vendor.testimonial1Name': 'ఎమిలీ జాన్సన్',
    'vendor.testimonial1Role': 'గూర్మే డిలైట్స్ క్యాటరింగ్ యజమాని',
    'vendor.testimonial2': 'ఫోటోగ్రాఫర్‌గా, నాకు క్లయింట్‌లను కనుగొనడం కష్టంగా ఉండేది. ఈ ప్లాట్‌ఫారమ్ నన్ను ఈవెంట్ ప్లానర్‌లతో కనెక్ట్ చేయడమే కాకుండా నా బుకింగ్‌లలో విలువైన అంతర్దృష్టులను కూడా అందించింది. సపోర్ట్ టీమ్ అద్భుతం!',
    'vendor.testimonial2Name': 'మైకేల్ చెన్',
    'vendor.testimonial2Role': 'ఫ్రీలాన్స్ ఫోటోగ్రాఫర్',
    'vendor.testimonial3': 'నేను నా డెకొరేషన్ సేవలను విస్తృత ప్రేక్షకులకు ప్రదర్శించగలిగాను. యూజర్-ఫ్రెండ్లీ ఇంటర్‌ఫేస్ మరియు రెస్పాన్సివ్ కస్టమర్ సర్వీస్ నా వ్యాపార వృద్ధిలో అన్ని తేడాను చేశాయి.',
    'vendor.testimonial3Name': 'సోఫియా పటేల్',
    'vendor.testimonial3Role': 'ఈవెంట్ డెకొరేటర్',
    'vendor.trustedPartners': 'మీలోవాతో విశ్వసనీయ భాగస్వాములు',
    'vendor.faqTitle': 'తరచుగా అడిగే ప్రశ్నలు',
    'vendor.faqSubtitle': 'ప్రారంభించడం గురించి మీకు తెలియవలసినవన్నీ',
    'vendor.marketSize': 'మార్కెట్ పరిమాణం',
    'vendor.marketValue': 'భారతీయ మార్కెట్ విలువ',
    'vendor.eventsPerDay': 'భారతదేశంలో రోజుకు జరిగే ఈవెంట్‌లు',
    'vendor.projected': 'ప్రొజెక్టెడ్ (2025–2028)',
    'vendor.footerTagline': 'విక్రేతలను క్లయింట్‌లతో కనెక్ట్ చేసే భారతదేశం యొక్క అతిపెద్ద ఈవెంట్ మరియు వినోద నిర్వహణ ప్లాట్‌ఫారమ్. ధృవీకరించిన లీడ్‌లు మరియు సురక్షిత చెల్లింపులతో మీ వ్యాపారాన్ని నిర్మించండి.',
    'vendor.contactUs': 'మమ్మల్ని సంప్రదించండి',
    'vendor.copyright': '© 2025 మీలోవా. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    'vendor.venue': 'వేదిక',
    'vendor.djSound': 'DJ సౌండ్',
    'vendor.cateringService': 'క్యాటరింగ్',
    'vendor.photography': 'ఫోటోగ్రఫీ',
    'vendor.decorationService': 'అలంకరణ',
    'vendor.musicBand': 'మ్యూజిక్ బ్యాండ్',
    
    // Dashboard
    'dashboard.title': 'డ్యాష్‌బోర్డ్',
    'dashboard.bookings': 'బుకింగ్‌లు',
    'dashboard.myServices': 'నా సేవలు',
    'dashboard.addService': 'కొత్త సేవను జోడించండి',
    'dashboard.wallet': 'వాలెట్',
    'dashboard.messages': 'సందేశాలు',
    'dashboard.settings': 'సెట్టింగ్‌లు',
    'dashboard.eAlbum': 'ఈ-ఆల్బమ్',
    
    // Login
    'login.title': 'తిరిగి స్వాగతం',
    'login.subtitle': 'మీ మీలోవా ఖాతాకు లాగిన్ అవ్వండి',
    'login.email': 'ఇమెయిల్',
    'login.password': 'పాస్‌వర్డ్',
    'login.button': 'లాగిన్',
    'login.noAccount': 'ఖాతా లేదా?',
    'login.signupLink': 'సైన్ అప్ చేయండి',
    
    // Signup
    'signup.title': 'ఖాతా సృష్టించండి',
    'signup.subtitle': 'ఈరోజు మీలోవాలో చేరండి',
    'signup.name': 'పూర్తి పేరు',
    'signup.email': 'ఇమెయిల్',
    'signup.password': 'పాస్‌వర్డ్',
    'signup.button': 'సైన్ అప్',
    'signup.hasAccount': 'ఇప్పటికే ఖాతా ఉందా?',
    'signup.loginLink': 'లాగిన్',
    
    // Vendor Registration
    'vendorReg.title': 'విక్రేత నమోదు',
    'vendorReg.profile': 'ప్రొఫైల్',
    'vendorReg.documents': 'పత్రాలు',
    'vendorReg.portfolio': 'పోర్ట్‌ఫోలియో',
    'vendorReg.pricing': 'ధర',
    'vendorReg.step': 'దశ',
    'vendorReg.businessName': 'వ్యాపార పేరు',
    'vendorReg.ownerName': 'యజమాని పేరు',
    'vendorReg.phone': 'ఫోన్ నంబర్',
    'vendorReg.category': 'సేవ వర్గం',
    'vendorReg.address': 'వ్యాపార చిరునామా',
    'vendorReg.description': 'వ్యాపార వివరణ',
    'vendorReg.previous': 'మునుపటి',
    'vendorReg.next': 'తదుపరి',
    'vendorReg.goToDashboard': 'డాష్‌బోర్డ్‌కు వెళ్లండి',
    'vendorReg.panCard': 'పాన్ కార్డ్',
    'vendorReg.aadhaarCard': 'ఆధార్ కార్డ్',
    'vendorReg.gstCertificate': 'GST సర్టిఫికేట్ (వర్తించినట్లయితే)',
    'vendorReg.businessLicense': 'వ్యాపార లైసెన్స్/నమోదు',
    'vendorReg.bankProof': 'బ్యాంక్ ఖాతా రుజువు',
    'vendorReg.workImages': 'పని ప్రదర్శన చిత్రాలు',
    'vendorReg.certificates': 'సర్టిఫికెట్లు మరియు అవార్డులు',
    'vendorReg.workHistory': 'పని చరిత్ర',
    'vendorReg.socialMedia': 'సోషల్ మీడియా లింక్‌లు',
    'vendorReg.serviceName': 'సేవ పేరు',
    'vendorReg.basePrice': 'ప్రాథమిక ధర (₹)',
    'vendorReg.capacity': 'సామర్థ్యం',
    'vendorReg.pricingDescription': 'ధర వివరణ',
    'vendorReg.advancePayment': 'ముందస్తు చెల్లింపు అవసరం (%)',
    'vendorReg.cancellationPolicy': 'రద్దు విధానం',
    'vendorReg.availability': 'లభ్యత',
    'vendorReg.uploadPan': 'పాన్ కార్డ్ యొక్క స్పష్టమైన కాపీని అప్‌లోడ్ చేయండి',
    'vendorReg.uploadAadhaar': 'ఆధార్ ముందు మరియు వెనుక అప్‌లోడ్ చేయండి',
    'vendorReg.uploadGst': 'GST నమోదు సర్టిఫికెట్‌ను అప్‌లోడ్ చేయండి',
    'vendorReg.uploadBusinessDoc': 'ఏదైనా వ్యాపార నమోదు పత్రాలు',
    'vendorReg.uploadBankProof': 'రద్దు చేసిన చెక్ లేదా బ్యాంక్ స్టేట్‌మెంట్',
    'vendorReg.uploadWorkImages': 'మీ పని యొక్క కనీసం 5 అధిక నాణ్యత చిత్రాలను అప్‌లోడ్ చేయండి (గరిష్టంగా 20 చిత్రాలు)',
    'vendorReg.uploadCertificates': 'ఏదైనా అవార్డులు, సర్టిఫికెట్లు లేదా సాధనలు',
    'vendorReg.workHistoryPlaceholder': 'మీ అనుభవం, ముఖ్యమైన ఈవెంట్‌లు, క్లయింట్‌లను వివరించండి...',
    'vendorReg.instagramPlaceholder': 'ఇన్‌స్టాగ్రామ్ ప్రొఫైల్ URL',
    'vendorReg.facebookPlaceholder': 'ఫేస్‌బుక్ పేజీ URL',
    'vendorReg.websitePlaceholder': 'వెబ్‌సైట్ URL (ఏదైనా ఉంటే)',
    'vendorReg.serviceNamePlaceholder': 'ఉదా: ప్రాథమిక ప్యాకేజీ, ప్రీమియం ప్యాకేజీ',
    'vendorReg.basePricePlaceholder': '50000',
    'vendorReg.capacityPlaceholder': '200 మంది',
    'vendorReg.pricingDescPlaceholder': 'ఈ ధరలో ఏమి ఉంది? ఏదైనా అదనపు ఛార్జీలు?',
    'vendorReg.advancePaymentPlaceholder': '30',
    'vendorReg.advancePaymentHelper': 'బుకింగ్ కోసం అవసరమైన ముందస్తు చెల్లింపు శాతం',
    'vendorReg.cancellationPlaceholder': 'మీ రద్దు మరియు రీఫండ్ విధానాన్ని వివరించండి',
    'vendorReg.availabilityPlaceholder': 'మీ పని రోజులు, గంటలు, బ్లాక్‌అవుట్ తేదీలు...',
    'vendorReg.registrationComplete': 'నమోదు పూర్తయింది!',
    'vendorReg.registrationSuccess': 'మీ విక్రేత ఖాతా విజయవంతంగా సృష్టించబడింది.',
    
    // Vendor Dashboard
    'vendorDash.title': 'విక్రేత డాష్‌బోర్డ్',
    'vendorDash.dashboard': 'డాష్‌బోర్డ్',
    'vendorDash.bookings': 'బుకింగ్‌లు',
    'vendorDash.services': 'నా సేవలు',
    'vendorDash.addService': 'కొత్త సేవ జోడించండి',
    'vendorDash.wallet': 'వాలెట్',
    'vendorDash.messages': 'సందేశాలు',
    'vendorDash.settings': 'సెట్టింగ్‌లు',
    'vendorDash.profile': 'ప్రొఫైల్',
    'vendorDash.logout': 'లాగ్ అవుట్',
    'vendorDash.totalEarnings': 'మొత్తం ఆదాయం',
    'vendorDash.activeBookings': 'యాక్టివ్ బుకింగ్‌లు',
    'vendorDash.totalClients': 'మొత్తం క్లయింట్లు',
    'vendorDash.pendingRequests': 'పెండింగ్ అభ్యర్థనలు',
    'vendorDash.fromLastMonth': 'గత నెల నుండి +20%',
    'vendorDash.fromLastWeek': 'గత వారం నుండి +3',
    'vendorDash.newThisMonth': 'ఈ నెలలో +8 కొత్త',
    'vendorDash.respondQuickly': 'త్వరగా స్పందించండి',
    'vendorDash.earningsOverview': 'ఆదాయ అవలోకనం',
    'vendorDash.earningsOverviewDesc': 'గత 6 నెలల మీ నెలవారీ ఆదాయం',
    'vendorDash.quickActions': 'త్వరిత చర్యలు',
    'vendorDash.addNewService': 'కొత్త సేవ జోడించండి',
    'vendorDash.viewBookings': 'బుకింగ్‌లు చూడండి',
    'vendorDash.checkMessages': 'సందేశాలు చూడండి',
    'vendorDash.myBookings': 'నా బుకింగ్‌లు',
    'vendorDash.myBookingsDesc': 'మీ రాబోయే మరియు గత బుకింగ్‌లను నిర్వహించండి',
    'vendorDash.weddingReception': 'వెడ్డింగ్ రిసెప్షన్',
    'vendorDash.bookingDate': 'తేదీ: 25 డిసెంబర్ 2025 | క్లయింట్: జాన్ డో',
    'vendorDash.viewDetailsBtn': 'వివరాలు చూడండి',
    'vendorDash.myServicesTitle': 'నా సేవలు',
    'vendorDash.myServicesDesc': 'ప్లాట్‌ఫారమ్‌లో మీరు జాబితా చేసిన సేవలు',
    'vendorDash.status': 'స్థితి',
    'vendorDash.active': 'యాక్టివ్',
    'vendorDash.edit': 'సవరించు',
    'vendorDash.view': 'చూడండి',
    'vendorDash.addServiceTitle': 'కొత్త సేవ జోడించండి',
    'vendorDash.addServiceDesc': 'ప్లాట్‌ఫారమ్‌లో కొత్త సేవను జాబితా చేయండి',
    'vendorDash.serviceName': 'సేవ పేరు',
    'vendorDash.serviceNamePlaceholder': 'ఉదా., వెడ్డింగ్ ఫోటోగ్రఫీ',
    'vendorDash.serviceDescription': 'వివరణ',
    'vendorDash.serviceDescPlaceholder': 'మీ సేవను వివరించండి...',
    'vendorDash.price': 'ధర (₹)',
    'vendorDash.serviceImages': 'సేవ చిత్రాలు',
    'vendorDash.clickToUpload': 'చిత్రాలను అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    'vendorDash.uploadLimit': 'PNG, JPG 10MB వరకు',
    'vendorDash.addServiceBtn': 'సేవ జోడించండి',
    'vendorDash.walletTitle': 'వాలెట్',
    'vendorDash.walletDesc': 'మీ ఆదాయం మరియు చెల్లింపులను నిర్వహించండి',
    'vendorDash.availableBalance': 'అందుబాటులో ఉన్న బ్యాలెన్స్',
    'vendorDash.withdrawFunds': 'నిధులను విత్‌డ్రా చేయండి',
    'vendorDash.recentTransactions': 'ఇటీవలి లావాదేవీలు',
    'vendorDash.paymentReceived': 'చెల్లింపు అందింది',
    'vendorDash.messagesTitle': 'సందేశాలు',
    'vendorDash.messagesDesc': 'మీ క్లయింట్‌లతో చాట్ చేయండి',
    'vendorDash.client': 'క్లయింట్',
    'vendorDash.lastMessagePreview': 'చివరి సందేశ ప్రివ్యూ...',
    'vendorDash.hoursAgo': '2 గంటల క్రితం',
    'vendorDash.profileSettings': 'ప్రొఫైల్ సెట్టింగ్‌లు',
    'vendorDash.businessName': 'వ్యాపార పేరు',
    'vendorDash.businessNamePlaceholder': 'మీ వ్యాపార పేరు',
    'vendorDash.email': 'ఇమెయిల్',
    'vendorDash.emailPlaceholder': 'your@email.com',
    'vendorDash.phone': 'ఫోన్',
    'vendorDash.phonePlaceholder': '+91 9876543210',
    'vendorDash.updateProfile': 'ప్రొఫైల్ అప్‌డేట్ చేయండి',
    'vendorDash.language': 'భాష',
    'vendorDash.selectLanguage': 'భాషను ఎంచుకోండి',
    'vendorDash.notifications': 'నోటిఫికేషన్‌లు',
    'vendorDash.emailNotifications': 'ఇమెయిల్ నోటిఫికేషన్‌లు',
    'vendorDash.smsNotifications': 'SMS నోటిఫికేషన్‌లు',
    'vendorDash.bookingAlerts': 'బుకింగ్ అలర్ట్‌లు',
    'vendorDash.weddingPhotography': 'వెడ్డింగ్ ఫోటోగ్రఫీ',
    'vendorDash.birthdayDecoration': 'పుట్టినరోజు అలంకరణ',
    'vendorDash.corporateEventCatering': 'కార్పొరేట్ ఈవెంట్ క్యాటరింగ్',
    
    // Customer Dashboard
    'customerDash.filterBy': 'ఫిల్టర్ చేయండి',
    'customerDash.eventType': 'ఈవెంట్ రకం',
    'customerDash.wedding': 'పెళ్లి',
    'customerDash.reception': 'రిసెప్షన్',
    'customerDash.birthdayParty': 'పుట్టినరోజు పార్టీ',
    'customerDash.ceremonies': 'వేడుకలు',
    'customerDash.anniversaries': 'వార్షికోత్సవాలు',
    'customerDash.privateParties': 'ప్రైవేట్ పార్టీలు',
    'customerDash.priceRange': 'ధర పరిధి',
    'customerDash.dateTime': 'తేదీ & సమయం',
    'customerDash.amenitiesFeatures': 'సౌకర్యాలు & ఫీచర్లు',
    'customerDash.discoverVenue': 'మీ పరిపూర్ణ వేదికను కనుగొనండి',
    'customerDash.viewDetails': 'వివరాలు చూడండి',
    'customerDash.requestService': 'సేవ అభ్యర్థన',
    'customerDash.logout': 'లాగ్ అవుట్',
    'customerDash.perfectFor': 'చిన్న పార్టీలకు అనువైనది',
    'customerDash.ac': 'ఎయిర్ కండిషనింగ్',
    'customerDash.parking': 'పార్కింగ్',
    'customerDash.catering': 'క్యాటరింగ్',
    'customerDash.wifi': 'వైఫై',
    'customerDash.sound': 'సౌండ్ సిస్టమ్',
    'customerDash.decoration': 'అలంకరణ',
    'customerDash.close': 'మూసివేయండి',
    'customerDash.about': 'గురించి',
    'customerDash.servicesOffered': 'అందించే సేవలు',
    'customerDash.capacity': 'సామర్థ్యం',
    'customerDash.priceRangeLabel': 'ధర పరిధి',
    'customerDash.amenities': 'సౌకర్యాలు',
    'customerDash.bookNow': 'ఇప్పుడే బుక్ చేయండి',
    'customerDash.guests': 'అతిథులు',
    'customerDash.meelova': 'Meelova',
    'customerDash.meelovaHi': 'మీలోవా',
    'customerDash.meelovaTe': 'మీలోవా',
    'customerDash.confirmBooking': 'బుకింగ్ నిర్ధారించండి',
    'customerDash.requestSent': 'మీ అభ్యర్థన పంపబడింది!',
    'customerDash.waitForStatus': 'దయచేసి విక్రేత మీ బుకింగ్‌ను నిర్ధారించే వరకు వేచి ఉండండి. స్థితి అప్‌డేట్ అయినప్పుడు మీకు నోటిఫికేషన్ వస్తుంది.',
    'customerDash.okGotIt': 'సరే, అర్థమైంది',
    'customerDash.cancel': 'రద్దు చేయండి',
    'customerDash.lights': 'లైట్లు',
    'customerDash.stage': 'స్టేజ్ సెటప్',
    'customerDash.floralDecor': 'పుష్ప అలంకరణ',
    'customerDash.videoScreen': 'వీడియో స్క్రీన్',
    
    // Vendor data translations
    'vendor.royalPalace': 'రాయల్ ప్యాలెస్ బ్యాంక్వెట్ హాల్',
    'vendor.royalPalaceDesc': 'మీ ప్రత్యేక క్షణాల కోసం అసాధారణ సేవ',
    'vendor.royalPalaceFull': 'రాయల్ ప్యాలెస్ బ్యాంక్వెట్ హాల్ పెళ్లిళ్లు, రిసెప్షన్లు మరియు కార్పొరేట్ ఈవెంట్ల కోసం ప్రపంచ స్థాయి సౌకర్యాలను అందించే ప్రీమియం వేదిక. 500+ అతిథుల సామర్థ్యం, సొగసైన అలంకరణ మరియు సెంట్రల్ AC, LED లైటింగ్ మరియు ప్రొఫెషనల్ సౌండ్ సిస్టమ్‌లతో సహా ఆధునిక సౌకర్యాలు.',
    'vendor.grandHeritage': 'గ్రాండ్ హెరిటేజ్ వెడ్డింగ్ వేదిక',
    'vendor.grandHeritageDesc': 'మీ ప్రత్యేక క్షణాల కోసం అసాధారణ సేవ',
    'vendor.grandHeritageFull': 'గ్రాండ్ హెరిటేజ్ ఆధునిక సౌకర్యాలతో సాంప్రదాయ సొగసును తెస్తుంది. సన్నిహిత పెళ్లిళ్లు మరియు భారీ రిసెప్షన్లకు అనువైనది. మీ ప్రత్యేక రోజు కోసం ప్రతి వివరాన్ని పరిపూర్ణంగా చేయడానికి మా అనుభవజ్ఞుల బృందం నిర్ధారిస్తుంది.',
    'vendor.premiumGarden': 'ప్రీమియం గార్డెన్ ఈవెంట్స్',
    'vendor.premiumGardenDesc': 'మీ ప్రత్యేక క్షణాల కోసం అసాధారణ సేవ',
    'vendor.premiumGardenFull': 'ప్రీమియం గార్డెన్ ఈవెంట్స్ అందంగా సజ్జీకరించిన తోటలతో అవుట్‌డోర్ వేడుకలలో ప్రత్యేకత. పగటి పెళ్లిళ్లు, పుట్టినరోజు పార్టీలు మరియు సహజ వాతావరణంతో థీమ్డ్ ఈవెంట్‌లకు అనువైనది.',
    'vendor.weddingVenue': 'పెళ్లి వేదిక',
    'vendor.receptionHall': 'రిసెప్షన్ హాల్',
    'vendor.corporateEvents': 'కార్పొరేట్ ఈవెంట్స్',
    'vendor.weddingService': 'పెళ్లి',
    'vendor.engagementService': 'నిశ్చితార్థం',
    'vendor.receptionService': 'రిసెప్షన్',
    'vendor.outdoorEvents': 'అవుట్‌డోర్ ఈవెంట్స్',
    'vendor.gardenWeddings': 'గార్డెన్ పెళ్లిళ్లు',
    'vendor.birthdayParties': 'పుట్టినరోజు పార్టీలు',
    'vendor.centralAc': 'సెంట్రల్ AC',
    'vendor.ledLighting': 'LED లైటింగ్',
    'vendor.soundSystem': 'సౌండ్ సిస్టమ్',
    'vendor.parkingAvailable': 'పార్కింగ్',
    'vendor.cateringAvailable': 'క్యాటరింగ్ అందుబాటులో',
    'vendor.gardenArea': 'గార్డెన్ ప్రాంతం',
    'vendor.decorativeLighting': 'అలంకార లైటింగ్',
    'vendor.inHouseCatering': 'ఇన్-హౌస్ క్యాటరింగ్',
    'vendor.valetParking': 'వేలెట్ పార్కింగ్',
    'vendor.bridalRoom': 'వధూ గది',
    'vendor.landscapedGarden': 'సజ్జీకరించిన తోట',
    'vendor.outdoorLighting': 'అవుట్‌డోర్ లైటింగ్',
    'vendor.gazebo': 'గేజిబో',
    'vendor.amplePar': 'పుష్కలమైన పార్కింగ్',
    'vendor.flexibleCatering': 'సౌలభ్య క్యాటరింగ్',
    'vendor.cashfree': 'క్యాష్‌ఫ్రీ',
    'vendor.upi': 'UPI',
    'vendor.cards': 'కార్డ్స్',
    
    // Vendor Dashboard History & Calendar
    'vendorDash.history': 'చరిత్ర',
    'vendorDash.historyDesc': 'మీ గత బుకింగ్‌లు మరియు లావాదేవీలను చూడండి',
    'vendorDash.calendar': 'క్యాలెండర్',
    'vendorDash.calendarDesc': 'మీ షెడ్యూల్ చేసిన ఈవెంట్‌లను చూడండి',
    'vendorDash.cashOnSpot': 'స్పాట్‌లో నగదు',
    'vendorDash.currentTransactions': 'ప్రస్తుత లావాదేవీలు',
    'vendorDash.noEventsToday': 'ఈ తేదీకి ఈవెంట్‌లు షెడ్యూల్ చేయబడలేదు',
    'vendorDash.completed': 'పూర్తయింది',
    'vendorDash.pending': 'పెండింగ్',
    'vendorDash.serviceUpdated': 'సేవ విజయవంతంగా అప్‌డేట్ చేయబడింది',
    'vendorDash.serviceDeleted': 'సేవ విజయవంతంగా తొలగించబడింది',
    'vendorDash.confirmDelete': 'మీరు ఖచ్చితంగా ఈ సేవను తొలగించాలనుకుంటున్నారా?',
    'vendorDash.editService': 'సేవను సవరించండి',
    'vendorDash.viewService': 'సేవ వివరాలు చూడండి',
    
    // Customer Dashboard additions
    'customerDash.history': 'బుకింగ్ చరిత్ర',
    'customerDash.historyDesc': 'మీ గత బుకింగ్‌లను చూడండి',
    'customerDash.packages': 'ప్యాకేజీలు',
    'customerDash.packagesDesc': 'ప్రత్యేక ఈవెంట్ ప్యాకేజీలను బ్రౌజ్ చేయండి',
    'customerDash.destinationServices': 'గమ్యస్థాన సేవలు',
    'customerDash.destinationServicesDesc': 'మీ గమ్యస్థానంలో అందుబాటులో ఉన్న సేవలు',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('meelova-language');
    return (savedLanguage as Language) || 'en';
  });

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('meelova-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
